import { dedupeRelations, importBindingMap, nearestSymbolByOffset, relation, simpleName, splitTypeList } from './common.js';

const PROVIDER = 'resolver-php-v1';
const CAPABILITIES = Object.freeze(['use-bindings', 'requires', 'inheritance', 'interfaces', 'constructor-types', 'imported-calls']);
const phpResolver = Object.freeze({ id:PROVIDER, capabilities:CAPABILITIES, enrich({source,facts}) {
  const text=String(source||'');const imports=parseImports(text);const bindings=importBindingMap(imports);const symbols=facts.symbols||[];
  return {provider:PROVIDER,capabilities:CAPABILITIES,imports:imports.map(({bindings:_bindings,...item})=>({...item,provider:PROVIDER,confidence:0.96})),relations:dedupeRelations([...classRelations(text,symbols,bindings),...constructorRelations(text,symbols,bindings),...callRelations(text,symbols,bindings)])};
}});
function parseImports(source){const result=[];for(const m of source.matchAll(/^\s*use\s+(function\s+)?([^;]+);/gm)){const qualified=m[2].trim().replaceAll('\\','/');const parts=qualified.split('/').filter(Boolean);const imported=parts.pop();const functionImport=Boolean(m[1]);result.push({specifier:functionImport?parts.join('/'):qualified,kind:functionImport?'use-function':'use',bindings:[{local:simpleName(imported),imported:simpleName(imported),kind:functionImport?'static':'named'}]});}for(const m of source.matchAll(/\b(?:require|require_once|include|include_once)\s*(?:\([^)]*)?['"]([^'"]+)['"]/g))result.push({specifier:m[1],kind:'require',bindings:[]});return result;}
function classRelations(source,symbols,bindings){const result=[];for(const m of source.matchAll(/\bclass\s+([A-Za-z_]\w*)(?:\s+extends\s+([A-Za-z_\\][\w\\]*))?(?:\s+implements\s+([^\{]+))?\s*\{/g)){const owner=symbols.find(item=>item.name===m[1])?.qualifiedName||m[1];if(m[2])result.push(relation(PROVIDER,'INHERITS',owner,m[2],bindings,{confidence:0.97}));for(const target of splitTypeList(m[3]))result.push(relation(PROVIDER,'IMPLEMENTS',owner,target,bindings,{confidence:0.97}));}return result;}
function constructorRelations(source,symbols,bindings){const result=[];for(const m of source.matchAll(/\bnew\s+([A-Z][A-Za-z0-9_]*)\s*\(/g))result.push(relation(PROVIDER,'USES_TYPE',nearestSymbolByOffset(source,symbols,m.index||0),m[1],bindings,{confidence:0.95}));return result;}
function callRelations(source,symbols,bindings){const result=[];for(const m of source.matchAll(/\b([A-Za-z_]\w*)\s*\(/g)){const item=bindings.get(m[1]);if(item?.kind==='static')result.push(relation(PROVIDER,'CALLS',nearestSymbolByOffset(source,symbols,m.index||0),m[1],bindings,{confidence:0.95}));}for(const m of source.matchAll(/\b([A-Z][A-Za-z0-9_]*)::([A-Za-z_]\w*)\s*\(/g)){const item=bindings.get(m[1]);if(item)result.push(relation(PROVIDER,'CALLS',nearestSymbolByOffset(source,symbols,m.index||0),m[2],new Map(),{moduleSpecifier:item.specifier,targetQualifiedName:simpleName(item.imported)+'.'+m[2],confidence:0.94}));}return result;}
export { phpResolver };
