import { fetchJson } from '../../api.js';
import { runButtonAction } from '../../action-state.js';
import { toast } from '../../components/toast.js';
import { pillHtml } from '../../components/pill.js';
import { get as getStore } from '../../store.js';
import { connectionLayerViews, connectionStateFor, connectionSummary, hasObservedMcpConnection } from '../../connection-state.js';
import { mountDesktopConnection } from './desktop-connection.js';
import { createChatGptSetupGuide } from './connection-guidance.js';
import { restartConnection } from './connection-recovery.js';
import { esc as escapeHtml } from '../../utils.js';
const connectorPayloads=new WeakMap();
export function mountConnector(container){container.innerHTML='<div class="connection-loading">Loading connection details…</div>';return loadConnector(container).catch(error=>{container.innerHTML=`<div class="empty">${escapeHtml(error instanceof Error?error.message:String(error))}</div>`;});}
async function loadConnector(container){const payload=await fetchJson('/api/connection');container.innerHTML='<div class="section connection-page"></div>';const page=container.querySelector('.connection-page');if(!payload||payload.ok===false){page.insertAdjacentHTML('beforeend','<div class="empty">Connection details could not be loaded.</div>');return;}connectorPayloads.set(container,payload);const dashboardState=getStore(),state=connectionViewState(payload,dashboardState);page.append(summaryCard(state),supportRow(state),layerDisclosure(state),setupGuideRegion(payload,state));const controls=document.createElement('section');controls.id='connectionControls';controls.className='connection-controls-section';page.appendChild(controls);await mountDesktopConnection(controls,{expanded:String(state.publicEndpoint?.status||'')==='disabled'});}
function connectionViewState(payload,dashboardState={}){return connectionStateFor({...dashboardState,mcpConnection:dashboardState.mcpConnection||payload.mcpConnection||{}});}
export function updateConnectorLiveState(container,dashboardState={}){const page=container.querySelector('.connection-page'),payload=connectorPayloads.get(container);if(!page||!payload)return false;const state=connectionViewState(payload,dashboardState);replaceRegion(page,'.connection-summary-card',summaryCard(state));replaceRegion(page,'.connection-support-row',supportRow(state));replaceRegion(page,'.connection-layer-disclosure',layerDisclosure(state),{preserveOpen:true});replaceRegion(page,'.connection-guide-region',setupGuideRegion(payload,state));return true;}
function summaryCard(state){const summary=connectionSummary(state);const action=primaryActionHtml(state);const card=document.createElement('section');card.className=`card connection-summary-card ${summary.tone}`;card.innerHTML=`<div class="card-head"><h3>ChatGPT connection</h3>${pillHtml(summary.label,summary.tone)}</div><div class="card-body connection-status-body"><div class="connection-status-copy"><h2>${escapeHtml(summary.title)}</h2><p>${escapeHtml(summary.message)}</p></div>${action?`<div class="connection-primary-action">${action}</div>`:''}</div>`;const setup=card.querySelector('[data-scroll-setup]');if(setup)setup.onclick=showConnectionSetup;const scroll=card.querySelector('[data-scroll-controls]');if(scroll)scroll.onclick=()=>revealConnectionSettings({focus:true});const restart=card.querySelector('[data-restart-connection]');if(restart)restart.onclick=()=>restartFromConnection(restart);return card;}
async function restartFromConnection(button){const result=await runButtonAction(button,{idleText:button.textContent||'Retry now',loadingText:'Retrying connection…',successText:'Retry started',errorText:'Review settings'},restartConnection);if(result?.ok){toast('Connection retry started. Rel.AI is checking the Secure MCP Tunnel.',{variant:'success'});return;}toast(result?.error||'The connection could not be retried.',{variant:'error'});revealConnectionSettings({focus:true});}
export function connectionPrimaryAction(state={}){const summary=connectionSummary(state),local=String(state.localService?.status||''),endpoint=String(state.publicEndpoint?.status||''),errorCode=String(state.error?.code||'');if(local==='failed'||local==='stopped')return{kind:'route',href:'#diagnostics',label:'Troubleshoot'};if(endpoint==='disabled')return{kind:'control',label:'Set up connection'};if(endpoint==='unavailable'){if(errorCode==='tunnel_authentication_failed')return{kind:'settings',label:'Replace runtime key'};if(errorCode==='tunnel_access_denied')return{kind:'settings',label:'Review key permissions'};if(errorCode==='tunnel_not_found')return{kind:'settings',label:'Review Tunnel ID'};return{kind:'restart',label:'Retry now'};}if(endpoint==='degraded')return{kind:'restart',label:'Retry now'};if(summary.tone==='working')return{kind:'none'};if(summary.tone==='bad'||summary.tone==='warn')return{kind:'route',href:'#diagnostics',label:'Troubleshoot'};return{kind:'route',href:'#tasks',label:'Open tasks'};}
function primaryActionHtml(state){const action=connectionPrimaryAction(state);if(action.kind==='none')return'';if(action.kind==='control')return`<button class="primary" type="button" data-scroll-setup>${escapeHtml(action.label)}</button>`;if(action.kind==='settings')return`<button class="primary" type="button" data-scroll-controls>${escapeHtml(action.label)}</button>`;if(action.kind==='restart'&&typeof window.relaiDesktop?.restartConnection==='function')return`<button class="primary" type="button" data-restart-connection>${escapeHtml(action.label)}</button>`;if(action.kind==='restart')return'<button class="primary" type="button" data-scroll-controls>Review connection settings</button>';return`<a class="buttonlike primary" href="${escapeHtml(action.href)}">${escapeHtml(action.label)}</a>`;}
function supportRow(state){const row=document.createElement('div'),action=connectionPrimaryAction(state);row.className='connection-support-row';const review=['restart','settings'].includes(action.kind)?'<button class="secondary compact-button" type="button" data-scroll-controls>Review settings</button>':'';const troubleshooting=action.href==='#diagnostics'||action.kind==='none'?'':'<a class="buttonlike secondary compact-button" href="#diagnostics">Troubleshooting</a>';row.innerHTML=`<button class="secondary compact-button" type="button" data-refresh-connection>Refresh status</button>${review}${troubleshooting}`;row.querySelector('[data-refresh-connection]').onclick=async()=>{try{const status=await window.relaiDesktop?.getStatus?.();if(status)window.dispatchEvent(new CustomEvent('relai:desktop-status-refresh',{detail:status}));}catch{}window.dispatchEvent(new CustomEvent('relai:dashboard-refresh'));toast('Refreshing connection status…',{variant:'info'});};const scroll=row.querySelector('[data-scroll-controls]');if(scroll)scroll.onclick=()=>revealConnectionSettings({focus:true});return row;}
function layerDisclosure(state){const details=document.createElement('details'),summary=connectionSummary(state);details.className='card connector-details connection-layer-disclosure';details.open=summary.tone==='bad'||summary.tone==='warn';details.innerHTML='<summary class="connector-details-summary"><span><strong>Connection check</strong><small>This computer, Secure MCP Tunnel, and ChatGPT</small></span><span aria-hidden="true">›</span></summary>';const path=document.createElement('div');path.className='connection-path';for(const layer of connectionLayerViews(state))path.appendChild(layerCard(layer));details.appendChild(path);return details;}
function layerCard(layer){const card=document.createElement('article');card.className=`connection-path-step ${layer.tone}`;card.innerHTML=`<div class="connection-layer-card-head"><span class="connection-layer-dot" aria-hidden="true"></span><div><h4>${escapeHtml(layer.title)}</h4><span class="connection-layer-state ${layer.tone}">${escapeHtml(layer.label)}</span></div></div><p>${escapeHtml(layer.description)}</p>`;return card;}
function connectionGuideMode(state={}){const client=state.mcpClient||{};if(hasObservedMcpConnection(client))return null;const authorization=String(state.chatgptReadiness?.status||''),clientStatus=String(client.status||'');if(authorization==='authentication_required'||authorization==='authentication_failed'||clientStatus==='reauthentication_required')return'reconnect';return'create';}
function setupGuideRegion(payload,state){const region=document.createElement('div');region.className='connection-guide-region';const mode=connectionGuideMode(state);if(!mode)return region;const card=document.createElement('section');card.className='card connection-guide-card';card.innerHTML=`<div class="card-head"><h3>${mode==='reconnect'?'Reconnect ChatGPT':'Connect ChatGPT'}</h3><span class="section-action">Connection setup</span></div>`;const body=document.createElement('div');body.className='card-body';body.appendChild(createChatGptSetupGuide({compact:true,mode,tunnelId:getStore().desktopStatus?.tunnelId||payload.tunnelId||'',connectorName:payload.connectorName||'Rel.AI MCP',workspaceAlias:getStore().config?.workspaces?.[0]?.alias||'myapp'}));card.appendChild(body);region.appendChild(card);return region;}
function showConnectionSetup(){const disclosure=revealConnectionSettings({scroll:false});const target=document.querySelector('.connection-guide-card')||disclosure||document.getElementById('connectionControls');target?.scrollIntoView({behavior:'smooth',block:'start'});}
function revealConnectionSettings({scroll=true,focus=false}={}){const controls=document.getElementById('connectionControls');const disclosure=controls?.querySelector('.connection-settings-disclosure');if(disclosure)disclosure.open=true;if(scroll)(disclosure||controls)?.scrollIntoView({behavior:'smooth',block:'start'});if(focus)window.requestAnimationFrame(()=>disclosure?.querySelector('input,select,textarea,button')?.focus({preventScroll:true}));return disclosure;}
function replaceRegion(page,selector,next,options={}){const current=page.querySelector(selector);if(!current)return;if(options.preserveOpen&&current instanceof HTMLDetailsElement&&next instanceof HTMLDetailsElement)next.open=current.open;if(!current.isEqualNode(next))current.replaceWith(next);}
