import { fetchJson } from '../../api.js';
import { toast } from '../../components/toast.js';
import { pillHtml } from '../../components/pill.js';
import { get as getStore } from '../../store.js';
import { connectionLayerViews, connectionStateFor, connectionSummary, isMcpAuthenticationReady } from '../../connection-state.js';
import { mountDesktopConnection } from './desktop-connection.js';
import { clientCapabilityViews } from '../../task-identity.js';
import { createChatGptSetupGuide } from './connection-guidance.js';
import { esc as escapeHtml } from '../../utils.js';
const connectorPayloads=new WeakMap();
export function mountConnector(container){container.innerHTML='<div class="connection-loading">Loading connection details…</div>';return loadConnector(container).catch(error=>{container.innerHTML=`<div class="empty">${escapeHtml(error instanceof Error?error.message:String(error))}</div>`;});}
async function loadConnector(container){const payload=await fetchJson('/api/connection');container.innerHTML='<div class="section connection-page"></div>';const page=container.querySelector('.connection-page');if(!payload||payload.ok===false){page.insertAdjacentHTML('beforeend','<div class="empty">Connection details could not be loaded.</div>');return;}connectorPayloads.set(container,payload);const dashboardState=getStore(),state=connectionViewState(payload,dashboardState);page.append(summaryCard(payload,state),supportRow(),layerDisclosure(state),setupGuideRegion(payload,state),connectionDetails(payload,dashboardState));const controls=document.createElement('section');controls.id='connectionControls';controls.className='connection-controls-section';page.appendChild(controls);await mountDesktopConnection(controls);}
function connectionViewState(payload,dashboardState={}){return connectionStateFor({...dashboardState,mcpConnection:payload.mcpConnection||dashboardState.mcpConnection||{}});}
export function updateConnectorLiveState(container,dashboardState={}){const page=container.querySelector('.connection-page'),payload=connectorPayloads.get(container);if(!page||!payload)return false;const state=connectionViewState(payload,dashboardState);replaceRegion(page,'.connection-summary-card',summaryCard(payload,state));replaceRegion(page,'.connection-layer-disclosure',layerDisclosure(state),{preserveOpen:true});replaceRegion(page,'.connection-guide-region',setupGuideRegion(payload,state));replaceRegion(page,'.connector-technical-details',connectionDetails(payload,dashboardState),{preserveOpen:true});return true;}
function summaryCard(payload,state){const summary=connectionSummary(state),tunnelId=String(payload.tunnelId||getStore().desktopStatus?.tunnelId||'');const card=document.createElement('section');card.className=`card connection-summary-card ${summary.tone}`;card.innerHTML=`<div class="card-head"><h3>ChatGPT connection</h3>${pillHtml(summary.label,summary.tone)}</div><div class="card-body connection-status-body"><div class="connection-status-copy"><h2>${escapeHtml(summary.title)}</h2><p>${escapeHtml(summary.message)}</p></div><div class="connection-field"><span class="field-caption">Secure tunnel</span><code class="connector-endpoint">${escapeHtml(tunnelId||'Not configured')}</code></div><div class="connection-primary-action">${primaryActionHtml(state)}</div></div>`;card.querySelector('[data-scroll-controls]')?.addEventListener('click',()=>document.getElementById('connectionControls')?.scrollIntoView({behavior:'smooth',block:'start'}));return card;}
export function connectionPrimaryAction(state={}){const summary=connectionSummary(state);if(state.publicEndpoint?.status!=='available')return{kind:'control',label:'Configure secure tunnel'};if(summary.tone==='bad'||summary.tone==='warn')return{kind:'route',href:'#diagnostics',label:'Open diagnostics'};return{kind:'route',href:'#tasks',label:'Open work sessions'};}
function primaryActionHtml(state){const action=connectionPrimaryAction(state);return action.kind==='control'?`<button class="primary" type="button" data-scroll-controls>${escapeHtml(action.label)}</button>`:`<a class="buttonlike primary" href="${escapeHtml(action.href)}">${escapeHtml(action.label)}</a>`;}
function supportRow(){const row=document.createElement('div');row.className='connection-support-row';row.innerHTML='<button class="secondary compact-button" type="button" data-refresh-connection>Refresh status</button><a class="buttonlike secondary compact-button" href="#diagnostics">Diagnostics</a>';row.querySelector('[data-refresh-connection]').addEventListener('click',()=>{window.dispatchEvent(new CustomEvent('relai:dashboard-refresh'));toast('Refreshing connection status…',{variant:'info'});});return row;}
function layerDisclosure(state){const details=document.createElement('details'),summary=connectionSummary(state);details.className='card connector-details connection-layer-disclosure';details.open=summary.tone==='bad'||summary.tone==='warn';details.innerHTML='<summary class="connector-details-summary"><span><strong>Connection layers</strong><small>Local service, Secure MCP Tunnel, and observed MCP activity</small></span><span aria-hidden="true">›</span></summary>';const path=document.createElement('div');path.className='connection-path';for(const layer of connectionLayerViews(state))path.appendChild(layerCard(layer));details.appendChild(path);return details;}
function layerCard(layer){const card=document.createElement('article');card.className=`connection-path-step ${layer.tone}`;card.innerHTML=`<div class="connection-layer-card-head"><span class="connection-layer-dot" aria-hidden="true"></span><div><h4>${escapeHtml(layer.title)}</h4><span class="connection-layer-state ${layer.tone}">${escapeHtml(layer.label)}</span></div></div><p>${escapeHtml(layer.description)}</p>`;return card;}
export function connectionGuideMode(state={}){if(isMcpAuthenticationReady(state))return null;const authorization=String(state.chatgptReadiness?.status||''),client=String(state.mcpClient?.status||'');if(authorization==='authentication_required'||authorization==='authentication_failed'||client==='reauthentication_required')return'reconnect';return'create';}
function setupGuideRegion(payload,state){const region=document.createElement('div');region.className='connection-guide-region';const mode=connectionGuideMode(state);if(!mode)return region;const card=document.createElement('section');card.className='card connection-guide-card';card.innerHTML=`<div class="card-head"><h3>${mode==='reconnect'?'Reconnect ChatGPT':'Connect ChatGPT'}</h3><span class="section-action">Secure MCP Tunnel</span></div>`;const body=document.createElement('div');body.className='card-body';body.appendChild(createChatGptSetupGuide({compact:true,mode,tunnelId:payload.tunnelId||getStore().desktopStatus?.tunnelId||'',workspaceAlias:getStore().config?.workspaces?.[0]?.alias||'myapp'}));card.appendChild(body);region.appendChild(card);return region;}
function connectionDetails(payload,dashboardState={}){const details=document.createElement('details');details.className='card connector-details connector-technical-details';const mcpConnection=dashboardState.mcpConnection||payload.mcpConnection||{},capability=clientCapabilityViews({...dashboardState,mcpConnection})[0];details.innerHTML=`<summary class="connector-details-summary"><span><strong>Connection details</strong><small>Local transport and observed client state</small></span><span aria-hidden="true">›</span></summary><div class="card-body connection-facts"><div class="connection-fact"><span class="connection-fact-label">Transport</span><span>OpenAI Secure MCP Tunnel</span></div><div class="connection-fact"><span class="connection-fact-label">Local MCP</span><span>Loopback bearer-authenticated</span></div><div class="connection-fact"><span class="connection-fact-label">MCP activity</span><span>${escapeHtml(mcpConnection.activityStatus||mcpConnection.status||'no requests')}</span></div><div class="connection-fact"><span class="connection-fact-label">Task support</span><span>${escapeHtml(capability?.capabilityLabel||'Native MCP Tasks: Unknown')}</span></div><div class="connection-fact"><span class="connection-fact-label">Execution mode</span><span>${escapeHtml(capability?.executionLabel?.replace('Execution mode: ','')||'standard')}</span></div></div>`;return details;}
function replaceRegion(page,selector,next,options={}){const current=page.querySelector(selector);if(!current)return;if(options.preserveOpen&&current instanceof HTMLDetailsElement&&next instanceof HTMLDetailsElement)next.open=current.open;if(!current.isEqualNode(next))current.replaceWith(next);}
