const MCP_PROTOCOL_VERSION = '2026-07-28';
const MCP_LEGACY_PROTOCOL_VERSIONS = Object.freeze(['2025-11-25']);
const TASKS_EXTENSION_ID = 'io.modelcontextprotocol/tasks';
const TASKS_EXTENSION_REVISION = '2026-07-28';

export {
  MCP_LEGACY_PROTOCOL_VERSIONS,
  MCP_PROTOCOL_VERSION,
  TASKS_EXTENSION_ID,
  TASKS_EXTENSION_REVISION
};
