import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import * as crypto from "node:crypto";
import { safeReadJson } from "./safety.js";

function stateDir() {
  return process.env.REL_AI_MCP_STATE_DIR || path.join(os.homedir(), ".rel-ai-mcp");
}

function getEnvPath() {
  return path.join(stateDir(), ".env");
}

function getConnectionProfilePath() {
  return path.join(stateDir(), "connection.json");
}

function ensureStateDir() {
  fs.mkdirSync(stateDir(), { recursive: true, mode: 0o700 });
}

function generateToken(bytes = 32) {
  return crypto.randomBytes(bytes).toString("base64url");
}

function parseEnvFile(text) {
  const result = {};
  for (const line of String(text || "").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const index = trimmed.indexOf("=");
    if (index <= 0) continue;
    const key = trimmed.slice(0, index).trim();
    let value = trimmed.slice(index + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

function readLaunchEnv() {
  const envPath = getEnvPath();
  if (!fs.existsSync(envPath)) return {};
  return parseEnvFile(fs.readFileSync(envPath, "utf8"));
}

function writeLaunchEnv(values) {
  ensureStateDir();
  const current = readLaunchEnv();
  const merged = { ...current, ...values };
  const lines = [
    "# Rel.AI MCP local launch secrets.",
    "# Keep this file private. It is generated by the Rel.AI MCP desktop app.",
    ...Object.entries(merged)
      .filter(([, value]) => value !== undefined && value !== null && String(value) !== "")
      .map(([key, value]) => `${key}=${JSON.stringify(String(value))}`)
  ];
  fs.writeFileSync(getEnvPath(), `${lines.join("\n")}\n`, { mode: 0o600 });
  return merged;
}

function readConnectionProfile() {
  const profilePath = getConnectionProfilePath();
  if (!fs.existsSync(profilePath)) return {};
  return safeReadJson(profilePath) || {};
}

function writeConnectionProfile(profile) {
  ensureStateDir();
  const current = readConnectionProfile();
  const next = {
    ...current,
    ...profile,
    updatedAt: new Date().toISOString()
  };
  fs.writeFileSync(getConnectionProfilePath(), `${JSON.stringify(next, null, 2)}\n`, { mode: 0o600 });
  return next;
}

function normalizePublicUrl(value) {
  let text = String(value || "").trim();
  if (!text) return "";
  while (text.endsWith("/")) text = text.slice(0, -1);
  if (!text.toLowerCase().startsWith("https://")) {
    throw new Error("Permanent public URL must start with https:// for ChatGPT Developer Mode.");
  }
  return text;
}

function localBaseUrl(host, port) {
  const safeHost = host === "0.0.0.0" ? "127.0.0.1" : host;
  return `http://${safeHost}:${port}`;
}

function tokenQuery(token) {
  return token ? `?token=${encodeURIComponent(token)}` : "";
}

function dashboardDataQuery(token) {
  const tokenPart = token ? `&token=${encodeURIComponent(token)}` : "";
  return `/api/dashboard/v10?limit=100&requireHttpToken=0${tokenPart}`;
}

function tokenState(token, showToken) {
  if (showToken) return token;
  if (token) return "set";
  return "missing";
}

function connectionTunnelMode(publicBaseUrl, tunnelProvider) {
  if (!publicBaseUrl) return "cloud connection required";
  if (tunnelProvider && tunnelProvider !== "none") return `cloud tunnel via ${tunnelProvider}`;
  return "configured HTTPS URL";
}

function connectionNextSteps(publicBaseUrl, baseForChatGPT, localUrl) {
  if (!publicBaseUrl) {
    return [
      "ChatGPT will not accept a localhost MCP endpoint for OAuth.",
      "Start a public HTTPS tunnel or configure --public-url with a stable HTTPS URL.",
      "After the cloud URL is ready, copy the generated /mcp URL into a ChatGPT app.",
      "Use the local dashboard only for setup, diagnostics, and workspace management."
    ];
  }
  return [
    "Keep Rel.AI MCP running on this machine while ChatGPT uses the app.",
    `Keep your tunnel or reverse proxy routing ${baseForChatGPT} to ${localUrl}.`,
    "In ChatGPT, create a custom app from Settings > Apps > Create. Admins can also use Workspace Settings > Apps > Create.",
    "Paste the COPY THIS FOR CHATGPT URL as the MCP endpoint and choose OAuth.",
    "When ChatGPT opens the sign-in page, enter your Rel.AI approval token to approve the app. Retry the existing app after token replacement; the endpoint does not change.",
    "In a chat, select the Rel.AI MCP app, then ask it to inspect a workspace before making changes."
  ];
}

function buildConnectionSummary({ host = "127.0.0.1", port = 3333, publicUrl = "", token = "", showToken = false, includeTokenInUrls = false, tunnelProvider = "" } = {}) {
  const localUrl = localBaseUrl(host, port);
  const publicBaseUrl = publicUrl ? normalizePublicUrl(publicUrl) : "";
  const baseForChatGPT = publicBaseUrl;
  const urlToken = includeTokenInUrls ? token : "";
  return {
    ok: true,
    localBaseUrl: localUrl,
    publicBaseUrl,
    dashboardUrl: `${localUrl}/dashboard${tokenQuery(urlToken)}`,
    dashboardDataUrl: `${localUrl}${dashboardDataQuery(urlToken)}`,
    localBearerMcpUrl: `${localUrl}/mcp`,
    localMcpUrl: `${localUrl}/mcp`,
    bearerMcpUrl: baseForChatGPT ? `${baseForChatGPT}/mcp` : "",
    // ChatGPT requires a reachable HTTPS endpoint for OAuth; localhost is kept for the dashboard/API only.
    chatgptMcpUrl: baseForChatGPT ? `${baseForChatGPT}/mcp` : "",
    chatgptHealthUrl: baseForChatGPT ? `${baseForChatGPT}/health` : "",
    chatgptAuthMode: "OAuth — ChatGPT signs in with your Rel.AI approval token.",
    oauthMetadataUrl: `${baseForChatGPT}/.well-known/oauth-protected-resource`,
    authHeader: token ? "Authorization: Bearer <REL_AI_MCP_TOKEN>" : "not configured",
    token: tokenState(token, showToken),
    tokenFile: getEnvPath(),
    profileFile: getConnectionProfilePath(),
    permanentUrlConfigured: Boolean(publicBaseUrl),
    tunnelProvider: tunnelProvider || "none",
    tunnelMode: connectionTunnelMode(publicBaseUrl, tunnelProvider),
    nextSteps: connectionNextSteps(publicBaseUrl, baseForChatGPT, localUrl)
  };
}

function printConnectionSummary(summary) {
  const lines = [
    "",
    "Rel.AI MCP is ready.",
    "",
    `Local dashboard:        ${summary.dashboardUrl}`,
    `Dashboard data check:   ${summary.dashboardDataUrl}`,
    `COPY THIS FOR CHATGPT:  ${summary.chatgptMcpUrl || "waiting for HTTPS tunnel"}`,
    `ChatGPT Auth:          OAuth (sign in with your approval token)`,
    `Health URL:            ${summary.chatgptHealthUrl || "waiting for HTTPS tunnel"}`,
    `Connection mode:       ${summary.tunnelMode || "cloud connection required"}`,
    `Local/API MCP only:     ${summary.localBearerMcpUrl}`,
    `Local/API Auth:         ${summary.authHeader}`,
    `Token file:       ${summary.tokenFile}`,
    `Profile file:     ${summary.profileFile}`,
    "",
    summary.permanentUrlConfigured
      ? "Permanent URL: configured. Use the COPY THIS FOR CHATGPT URL above. You should not need to recreate the ChatGPT app unless that URL changes."
      : "Permanent URL: not configured. ChatGPT requires HTTPS. Start a tunnel with --public, or set --public-url https://your-domain.example.com for a stable connector URL.",
    "",
    "Important:",
    "  - Create or update a ChatGPT app only after the HTTPS /mcp URL is available.",
    "  - Choose Authentication: OAuth, then enter your Rel.AI approval token when ChatGPT opens the sign-in page.",
    "  - Select the Rel.AI MCP app in a chat before asking it to inspect a workspace.",
    "  - Do not open /mcp in the browser as a dashboard. Use /dashboard instead.",
    "  - If the dashboard says Connecting, open the Dashboard data check URL above.",
    "  - OAuth requires the server to be reachable over HTTPS; localhost is invalid for ChatGPT.",
    "",
    "Next steps:",
    ...summary.nextSteps.map((step, index) => `  ${index + 1}. ${step}`),
    ""
  ];
  console.error(lines.join("\n"));
}

export { stateDir, getEnvPath, getConnectionProfilePath, generateToken, readLaunchEnv, writeLaunchEnv, readConnectionProfile, writeConnectionProfile, normalizePublicUrl, localBaseUrl, buildConnectionSummary, printConnectionSummary };
