const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const crypto = require("node:crypto");
const { safeReadJson } = require("./safety");

function stateDir() {
  return process.env.REL_AI_MCP_STATE_DIR || path.join(os.homedir(), ".rel-ai-mcp");
}

function getEnvPath() {
  return path.join(stateDir(), ".env");
}

function getConnectionProfilePath() {
  return path.join(stateDir(), "connection.json");
}

function ensureStateDir() {
  fs.mkdirSync(stateDir(), { recursive: true, mode: 0o700 });
}

function generateToken(bytes = 32) {
  return crypto.randomBytes(bytes).toString("base64url");
}

function parseEnvFile(text) {
  const result = {};
  for (const line of String(text || "").split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const index = trimmed.indexOf("=");
    if (index <= 0) continue;
    const key = trimmed.slice(0, index).trim();
    let value = trimmed.slice(index + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  }
  return result;
}

function readLaunchEnv() {
  const envPath = getEnvPath();
  if (!fs.existsSync(envPath)) return {};
  return parseEnvFile(fs.readFileSync(envPath, "utf8"));
}

function writeLaunchEnv(values) {
  ensureStateDir();
  const current = readLaunchEnv();
  const merged = { ...current, ...values };
  const lines = [
    "# Rel.AI MCP local launch secrets.",
    "# Keep this file private. It is generated by rel-ai-mcp-launch.",
    ...Object.entries(merged)
      .filter(([, value]) => value !== undefined && value !== null && String(value) !== "")
      .map(([key, value]) => `${key}=${JSON.stringify(String(value))}`)
  ];
  fs.writeFileSync(getEnvPath(), `${lines.join("\n")}\n`, { mode: 0o600 });
  return merged;
}

function readConnectionProfile() {
  const profilePath = getConnectionProfilePath();
  if (!fs.existsSync(profilePath)) return {};
  return safeReadJson(profilePath) || {};
}

function writeConnectionProfile(profile) {
  ensureStateDir();
  const current = readConnectionProfile();
  const next = {
    ...current,
    ...profile,
    updatedAt: new Date().toISOString()
  };
  fs.writeFileSync(getConnectionProfilePath(), `${JSON.stringify(next, null, 2)}\n`, { mode: 0o600 });
  return next;
}

function normalizePublicUrl(value) {
  const text = String(value || "").trim();
  if (!text) return "";
  const withoutSlash = text.replace(/\/+$/, "");
  if (!/^https:\/\//i.test(withoutSlash)) {
    throw new Error("Permanent public URL must start with https:// for ChatGPT Developer Mode.");
  }
  return withoutSlash;
}

function localBaseUrl(host, port) {
  const safeHost = host === "0.0.0.0" ? "127.0.0.1" : host;
  return `http://${safeHost}:${port}`;
}

function buildConnectionSummary({ host = "127.0.0.1", port = 3333, publicUrl = "", token = "", showToken = false } = {}) {
  const localUrl = localBaseUrl(host, port);
  const publicBaseUrl = publicUrl ? normalizePublicUrl(publicUrl) : "";
  const baseForChatGPT = publicBaseUrl || localUrl;
  return {
    ok: true,
    localBaseUrl: localUrl,
    publicBaseUrl,
    dashboardUrl: `${localUrl}/dashboard${token ? `?token=${encodeURIComponent(token)}` : ""}`,
    localMcpUrl: `${localUrl}/mcp`,
    chatgptMcpUrl: `${baseForChatGPT}/mcp`,
    chatgptHealthUrl: `${baseForChatGPT}/health`,
    authHeader: token ? "Authorization: Bearer <REL_AI_MCP_TOKEN>" : "not configured",
    token: showToken ? token : token ? "set" : "missing",
    tokenFile: getEnvPath(),
    profileFile: getConnectionProfilePath(),
    permanentUrlConfigured: Boolean(publicBaseUrl),
    nextSteps: publicBaseUrl
      ? [
          "Keep the local Rel.AI MCP server running on this machine.",
          "Keep your tunnel/reverse proxy routing the public URL to http://127.0.0.1:3333.",
          "In ChatGPT Developer Mode, create or update one app that points to the chatgptMcpUrl.",
          "Use the bearer token from the local token file. Do not paste it in public places."
        ]
      : [
          "For local testing, use the dashboardUrl on this machine.",
          "For ChatGPT Developer Mode, configure a stable HTTPS tunnel and run this launcher again with --public-url https://your-domain.example.com.",
          "Do not rely on random temporary ngrok URLs if you want one permanent ChatGPT app."
        ]
  };
}

function printConnectionSummary(summary) {
  const lines = [
    "",
    "Rel.AI MCP is ready.",
    "",
    `Local dashboard: ${summary.dashboardUrl}`,
    `Local MCP URL:    ${summary.localMcpUrl}`,
    `ChatGPT MCP URL:  ${summary.chatgptMcpUrl}`,
    `Health URL:       ${summary.chatgptHealthUrl}`,
    `Auth:             ${summary.authHeader}`,
    `Token file:       ${summary.tokenFile}`,
    `Profile file:     ${summary.profileFile}`,
    "",
    summary.permanentUrlConfigured
      ? "Permanent URL: configured. You should not need to recreate the ChatGPT app unless this URL or token changes."
      : "Permanent URL: not configured. Add one with --public-url https://your-domain.example.com.",
    "",
    "Next steps:",
    ...summary.nextSteps.map((step, index) => `  ${index + 1}. ${step}`),
    ""
  ];
  console.error(lines.join("\n"));
}

module.exports = {
  stateDir,
  getEnvPath,
  getConnectionProfilePath,
  generateToken,
  readLaunchEnv,
  writeLaunchEnv,
  readConnectionProfile,
  writeConnectionProfile,
  normalizePublicUrl,
  buildConnectionSummary,
  printConnectionSummary
};
