import * as fs from 'node:fs';
import * as path from 'node:path';
import * as crypto from 'node:crypto';
import { safeReadJson } from './safety.js';
import { writeJsonAtomic, writeTextAtomic } from './durableState.js';
import { defaultStateDir } from './stateLayout.js';

function stateDir(){return process.env.REL_AI_MCP_STATE_DIR||defaultStateDir();}
function getEnvPath(){return path.join(stateDir(),'.env');}
function getConnectionProfilePath(){return path.join(stateDir(),'connection.json');}
function ensureStateDir(){fs.mkdirSync(stateDir(),{recursive:true,mode:0o700});}
/** @knipdynamic Intentional dynamic/cross-workspace module boundary. */
export function generateToken(bytes=32){return crypto.randomBytes(bytes).toString('base64url');}
function parseEnvFile(text){const result={};for(const line of String(text||'').split(/\r?\n/)){const trimmed=line.trim();if(!trimmed||trimmed.startsWith('#'))continue;const index=trimmed.indexOf('=');if(index<=0)continue;const key=trimmed.slice(0,index).trim();let value=trimmed.slice(index+1).trim();if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))value=value.slice(1,-1);result[key]=value;}return result;}
function readLaunchEnv(){const envPath=getEnvPath();if(!fs.existsSync(envPath))return{};return parseEnvFile(fs.readFileSync(envPath,'utf8'));}
/** @knipdynamic Intentional dynamic/cross-workspace module boundary. */
export function writeLaunchEnv(values,{replace=false}={}){ensureStateDir();const current=replace?{}:readLaunchEnv(),merged={...current,...values};const lines=['# Rel.AI MCP local launch secrets.','# Keep this file private. It is generated by the Rel.AI MCP desktop app.',...Object.entries(merged).filter(([,value])=>value!==undefined&&value!==null&&String(value)!=='').map(([key,value])=>`${key}=${JSON.stringify(String(value))}`)];writeTextAtomic(getEnvPath(),`${lines.join('\n')}\n`,{mode:0o600,backup:true});return merged;}
function readConnectionProfile(){const profilePath=getConnectionProfilePath();if(!fs.existsSync(profilePath))return{};return safeReadJson(profilePath)||{};}
function writeConnectionProfile(profile,{replace=false}={}){ensureStateDir();const current=replace?{}:readConnectionProfile(),next={...current,...profile,updatedAt:new Date().toISOString()};for(const[key,value]of Object.entries(next)){if(value===null||value===undefined||value==='')delete next[key];}writeJsonAtomic(getConnectionProfilePath(),next,{mode:0o600,backup:true});return next;}
function localBaseUrl(host,port){const safeHost=host==='0.0.0.0'?'127.0.0.1':host;return`http://${safeHost}:${port}`;}
function tokenQuery(token){return token?`?token=${encodeURIComponent(token)}`:'';}
function dashboardDataQuery(token){const tokenPart=token?`&token=${encodeURIComponent(token)}`:'';return`/api/dashboard/v10?limit=100&requireHttpToken=0${tokenPart}`;}
function tokenState(token,showToken){return showToken?token:token?'set':'missing';}
function buildConnectionSummary({host='127.0.0.1',port=3333,token='',showToken=false,includeTokenInUrls=false,tunnelId='',tunnelProvider='openai-secure-mcp'}={}){const localUrl=localBaseUrl(host,port),urlToken=includeTokenInUrls?token:'',normalizedTunnelId=String(tunnelId||'').trim();return{ok:true,localBaseUrl:localUrl,publicBaseUrl:'',dashboardUrl:`${localUrl}/dashboard${tokenQuery(urlToken)}`,dashboardDataUrl:`${localUrl}${dashboardDataQuery(urlToken)}`,localBearerMcpUrl:`${localUrl}/mcp`,localMcpUrl:`${localUrl}/mcp`,bearerMcpUrl:'',chatgptMcpUrl:'',chatgptHealthUrl:'',chatgptAuthMode:'OpenAI Secure MCP Tunnel; the local hop uses Rel.AI bearer authentication.',oauthMetadataUrl:'',authHeader:token?'Authorization: Bearer <REL_AI_MCP_TOKEN>':'not configured',token:tokenState(token,showToken),tokenFile:getEnvPath(),profileFile:getConnectionProfilePath(),permanentUrlConfigured:false,tunnelId:normalizedTunnelId,tunnelProvider,tunnelMode:normalizedTunnelId?'OpenAI Secure MCP Tunnel':'not configured',nextSteps:['Keep Rel.AI running while ChatGPT uses this computer.','In ChatGPT, add or edit the Rel.AI MCP integration and choose the Tunnel connection option.',normalizedTunnelId?`Select or enter ${normalizedTunnelId}.`:'Create an OpenAI Secure MCP Tunnel and save its tunnel ID in Rel.AI Connection settings.','Enable Rel.AI MCP in the chat, then start with a read-only repository request.']};}
export { stateDir, readLaunchEnv, readConnectionProfile, writeConnectionProfile, buildConnectionSummary };
