const ORDER = ["read-only", "patch", "test", "pr", "admin"];
const TOOL_LEVEL = {
  relai_version: "read-only",
  relai_config: "read-only",
  relai_audit_tail: "read-only",
  relai_dashboard_summary: "read-only",
  relai_dashboard_open: "read-only",
  relai_task_status: "read-only",
  relai_session_diff: "read-only",
  relai_session_changed_files: "read-only",
  relai_session_test_summary: "read-only",
  relai_session_export: "read-only",
  relai_repo_profile: "read-only",
  relai_repo_relevant_files: "read-only",
  relai_repo_test_suggestions: "read-only",
  relai_approval_read: "read-only",
  relai_approval_list: "read-only",
  relai_approval_status: "read-only",
  relai_task_list: "read-only",
  relai_plan_create: "patch",
  relai_plan_list: "read-only",
  relai_plan_read: "read-only",
  relai_plan_update: "patch",
  relai_plan_step_update: "patch",
  relai_plan_step_append: "patch",
  relai_index_build: "read-only",
  relai_index_stats: "read-only",
  relai_index_search: "read-only",
  relai_task_bootstrap: "patch",
  relai_issue_to_pr_bootstrap: "patch",
  relai_ci_repair_snapshot: "pr",
  relai_ci_watch: "pr",
  relai_task_run: "test",
  relai_task_stop: "patch",
  relai_task_resume: "patch",
  relai_task_split: "patch",
  relai_subtask_create: "patch",
  relai_subtask_list: "read-only",
  relai_subtask_read: "read-only",
  relai_subtask_run: "test",
  relai_subtask_merge_back: "pr",
  relai_conflict_check: "read-only",
  relai_agent_review_diff: "read-only",
  relai_pr_review_summary: "pr",
  relai_agent_review_pr: "pr",
  relai_task_graph: "read-only",
  relai_multiagent_status: "read-only",
  relai_task_read: "read-only",
  relai_workspace_tree: "read-only",
  relai_workspace_profile: "read-only",
  relai_read_files: "read-only",
  relai_search: "read-only",
  relai_context_pack: "read-only",
  relai_git_status: "read-only",
  relai_git_diff: "read-only",
  relai_git_log: "read-only",
  relai_git_show: "read-only",
  relai_job_status: "read-only",
  relai_job_list: "read-only",
  relai_task_start: "patch",
  relai_task_step: "patch",
  relai_task_update: "patch",
  relai_task_worktree_create: "patch",
  relai_approval_request: "patch",
  relai_approval_resolve: "patch",
  relai_approval_grant: "patch",
  relai_approval_deny: "patch",
  relai_lock_acquire: "patch",
  relai_lock_release: "patch",
  relai_lock_list: "read-only",
  relai_worktree_list: "read-only",
  relai_write_file: "patch",
  relai_apply_patch: "patch",
  relai_create_branch: "patch",
  relai_switch_branch: "patch",
  relai_run_test: "test",
  relai_run_test_matrix: "test",
  relai_run_command: "test",
  relai_apply_patch_and_run: "test",
  relai_patch_test_loop: "test",
  relai_job_start_command: "test",
  relai_docker_run: "test",
  relai_commit_all: "pr",
  relai_push_branch: "pr",
  relai_create_pr: "pr",
  relai_pr_checks: "pr",
  relai_pr_watch_checks: "pr",
  relai_ci_repair_run: "pr",
  relai_task_worktree_remove: "admin",
  relai_git_reset_worktree: "admin",
  relai_job_cancel: "admin"
};

function enforcePermission(config, toolName) {
  const configured = String(config.permissionProfile || "pr");
  const need = TOOL_LEVEL[toolName] || "admin";
  const current = ORDER.indexOf(configured);
  const required = ORDER.indexOf(need);
  if (current === -1) throw new Error(`Invalid permissionProfile '${configured}'. Use one of: ${ORDER.join(", ")}.`);
  if (current < required) throw new Error(`Tool '${toolName}' requires permission profile '${need}', current profile is '${configured}'.`);
}

module.exports = { enforcePermission, TOOL_LEVEL, ORDER };
