const DEFAULT_TASK_ACTIVITY_IDLE_MS = 5 * 60 * 1000;
const MIN_TASK_ACTIVITY_IDLE_MS = 15_000;
const MAX_TASK_ACTIVITY_IDLE_MS = 10 * 60 * 1000;

const DEFAULT_TASK_STALE_MS = 8 * 60 * 60 * 1000;
export {
  DEFAULT_TASK_ACTIVITY_IDLE_MS,
  MIN_TASK_ACTIVITY_IDLE_MS,
  MAX_TASK_ACTIVITY_IDLE_MS,
  DEFAULT_TASK_STALE_MS
};
