// @ts-check

import { MAX_BATCH_EDITS } from '../editLimits.js';
import { OPERATION_IDS as OP } from './operationIds.js';

/** @typedef {import('../../types/boundaries.d.ts').ToolDefinitionMetadata} ToolDefinitionMetadata */
/** @typedef {Omit<ToolDefinitionMetadata, 'annotations' | 'connectorStrip' | 'groups' | 'behavior' | 'dashboard' | 'outputSchema'> & { annotations?: Partial<ToolDefinitionMetadata['annotations']>, connectorStrip?: string[], groups?: import('../../types/boundaries.d.ts').ToolGroup[], behavior?: Partial<ToolDefinitionMetadata['behavior']>, dashboard?: Partial<ToolDefinitionMetadata['dashboard']>, outputSchema?: import('../../types/boundaries.d.ts').JsonSchema }} ToolDefinitionInput */

/** @type {ToolDefinitionInput[]} */
const OPERATION_DEFINITION_VALUES = [
  {
    name: OP.WORK_BEGIN,
    title: "Start Logical Task",
    description: "Create an independent workspace-bound Rel.AI task and return its opaque work_id plus compact repository bootstrap context. Call this once for each unrelated ChatGPT task. Subsequent task-scoped tools require work_id and resolve the bound workspace automatically; workspace may be supplied only as an ownership assertion.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"title":{"type":"string","minLength":1,"maxLength":100},"objective":{"type":"string","minLength":1,"maxLength":500},"bootstrap":{"type":"string","enum":["compact","full","none"],"description":"Initial repository context returned with the task. Defaults to compact."},"instructionPath":{"type":"string","maxLength":1000,"description":"Optional workspace-relative file or directory used to discover applicable nested AGENTS.md instructions."}},"required":["workspace"],"additionalProperties":false},
    handlerName: 'startTask',
    behavior: {"taskScope":"none"},
    dashboard: {"category":"Workflow"}
  },
  {
    name: OP.SNAPSHOT,
    title: "Repository Overview",
    description: "Read-only. Compact repository overview: file tree, manifests, detected checks, and project hints.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"maxEntries":{"type":"number","minimum":1,"maximum":20000},"includeFiles":{"type":"boolean"}},"required":["workspace"],"additionalProperties":false},
    handlerName: 'repoSnapshot',
    behavior: {"audit":"snapshot"},
  },
  {
    name: OP.READ,
    title: "Read Local Repo Paths",
    description: "Read-only. Batch-read files or directory summaries, load one discovered project/user skill by name, retrieve one task-scoped outputRef returned by a truncated relai_exec result, or return one exact file as a private MCP resource_link for transfer/download. Ordinary hidden and Git-ignored files can be read when explicitly targeted; snapshot exclusions are not direct-access restrictions. Secret-bearing paths remain blocked. Use asResource:true with exactly one paths entry for whole-file transfer; startLine/endLine and ranges remain text-only. guidanceMode accepts full, compact, or none.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"paths":{"type":"array","items":{"type":"string","minLength":1,"maxLength":1000},"minItems":1,"maxItems":100},"outputRef":{"type":"string","pattern":"^spill_[A-Za-z0-9_-]{20,80}$"},"maxBytes":{"type":"number","minimum":1000,"maximum":10485760},"maxEntries":{"type":"number","minimum":1,"maximum":20000},"startLine":{"type":"number","minimum":1,"maximum":10000000},"endLine":{"type":"number","minimum":1,"maximum":10000000},"ranges":{"type":"array","items":{"type":"object","properties":{"path":{"type":"string","minLength":1,"maxLength":1000},"startLine":{"type":"number","minimum":1,"maximum":10000000},"endLine":{"type":"number","minimum":1,"maximum":10000000}},"required":["path"],"additionalProperties":false},"minItems":1,"maxItems":100},"skill":{"type":"string","minLength":1,"maxLength":80},"guidanceMode":{"type":"string","enum":["full","compact","none"]},"asResource":{"type":"boolean","description":"Return exactly one paths file as a private MCP resource_link for transfer or download instead of text content."}},"required":["workspace"],"anyOf":[{"required":["paths"]},{"required":["ranges"]},{"required":["skill"]},{"required":["outputRef"]}],"additionalProperties":false},
    handlerName: 'read',
    behavior: {"audit":"read"},
  },
  {
    name: OP.SEARCH_TEXT,
    title: "Search Workspace Text",
    description: "Read-only. Search tracked and untracked workspace files. Pass pattern for one search or queries for up to four independent searches that Rel.AI fans out inside one tool call. Auto mode is the default: focused searches receive broader context, while noisy searches receive smaller prioritized ranges. Compact and context modes remain explicit deterministic overrides.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"pattern":{"type":"string","minLength":1,"maxLength":1000},"queries":{"type":"array","items":{"type":"string","minLength":1,"maxLength":1000},"minItems":1,"maxItems":4},"glob":{"type":"string","maxLength":256},"fixed":{"type":"boolean"},"ignoreCase":{"type":"boolean"},"maxResults":{"type":"number","minimum":1,"maximum":1000},"mode":{"type":"string","enum":["auto","compact","context"]},"contextBefore":{"type":"number","minimum":0,"maximum":100},"contextAfter":{"type":"number","minimum":0,"maximum":100},"groupByFile":{"type":"boolean"},"mergeOverlaps":{"type":"boolean"},"maxFiles":{"type":"number","minimum":1,"maximum":200},"maxRangesPerFile":{"type":"number","minimum":1,"maximum":100},"maxRangeLines":{"type":"number","minimum":1,"maximum":1000},"maxBytes":{"type":"number","minimum":1000,"maximum":393216}},"required":["workspace"],"oneOf":[{"required":["pattern"],"not":{"required":["queries"]}},{"required":["queries"],"not":{"required":["pattern"]}}],"additionalProperties":false},
    handlerName: 'search',
  },
  {
    name: OP.INSPECT,
    title: "Code Intelligence",
    description: "Read-only. Hybrid code intelligence that combines language-server semantic authority with Rel.AI's persistent local Tree-sitter, graph, FTS5, and Zoekt repository analysis. Inspect definitions, references, hover/type information, implementations, structural impact, affected tests, architecture boundaries, entry points, hotspots, dependency layers, graph communities, and provider health. Language-server failures degrade to native Repository Intelligence when a native answer is available.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"action":{"type":"string","enum":["symbol","definition","references","hover","implementation","related","impact","trace","diagnostics","architecture"]},"symbol":{"type":"string","minLength":1,"maxLength":256},"path":{"type":"string","minLength":1,"maxLength":1000},"line":{"type":"number","minimum":1,"maximum":10000000},"column":{"type":"number","minimum":1,"maximum":10000000},"query":{"type":"string","minLength":1,"maxLength":1000},"paths":{"type":"array","items":{"type":"string"},"minItems":1,"maxItems":100},"maxResults":{"type":"number","minimum":1,"maximum":1000},"maxDepth":{"type":"number","minimum":1,"maximum":8},"maxFiles":{"type":"number","minimum":1,"maximum":20000}},"required":["workspace","action"],"additionalProperties":false},
    handlerName: 'codeInspect',
    groups: ["audit"],
    behavior: {"longRunning":true},
  },
  {
    name: OP.EXEC,
    title: "Run Workspace Command",
    description: "Run a one-shot development command directly in the configured visible workspace. Mutating or uncertain commands are serialized against other workspace writes; provably read-only direct commands can overlap safely. Use command for shell syntax, or executable + argv (+ optional input) for shell-free execution that preserves quotes, backticks, dollar signs, and multiline script text exactly. Returns exit status, bounded stdout and stderr, timing, and detected file changes. cwd is workspace-relative. A successful result does not replace final relai_validate checks validation.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"command":{"type":"string","minLength":1,"maxLength":20000},"executable":{"type":"string","minLength":1,"maxLength":1000},"argv":{"type":"array","items":{"type":"string","maxLength":20000},"maxItems":100},"input":{"type":"string","maxLength":1048576},"cwd":{"type":"string"},"timeoutMs":{"type":"number","minimum":1000,"maximum":86400000},"env":{"type":"object","additionalProperties":{"type":"string"}},"maxOutputBytes":{"type":"number","minimum":1000,"maximum":16777216}},"required":["workspace"],"oneOf":[{"required":["command"],"not":{"anyOf":[{"required":["executable"]},{"required":["argv"]},{"required":["input"]}]}},{"required":["executable"],"not":{"required":["command"]}}],"additionalProperties":false},
    handlerName: 'exec',
    behavior: {"audit":"exec","cache":"workspace","longRunning":true,"concurrencyScope":"mutation"},
  },
  {
    name: OP.PROCESS_START,
    title: "Start Managed Process",
    description: "Start a persistent service, watcher, or interactive program with stable identity, bounded persistent logs, interactive input, and workspace/task attribution. Set pty:true only with kind:interactive to allocate a real pseudo-terminal; columns/rows default to 80x24 and can be resized later through action write. Prefer executable + argv (+ optional initial input) for shell-free startup; use command only when shell syntax is deliberately required. One-shot tests, builds, checks, and release gates must use relai_exec or relai_validate with action 'checks' instead.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"command":{"type":"string","minLength":1,"maxLength":20000},"executable":{"type":"string","minLength":1,"maxLength":1000},"argv":{"type":"array","items":{"type":"string","maxLength":20000},"maxItems":100},"input":{"type":"string","maxLength":1048576},"cwd":{"type":"string"},"env":{"type":"object","additionalProperties":{"type":"string"}},"label":{"type":"string","maxLength":120},"kind":{"type":"string","enum":["service","watcher","interactive"]},"purpose":{"type":"string","minLength":1,"maxLength":300},"reuseExisting":{"type":"boolean"},"pty":{"type":"boolean"},"columns":{"type":"number","minimum":1,"maximum":1000},"rows":{"type":"number","minimum":1,"maximum":1000},"startupWaitMs":{"type":"number","minimum":0,"maximum":30000},"maxLogBytes":{"type":"number","minimum":65536,"maximum":268435456}},"required":["workspace","kind","purpose"],"oneOf":[{"required":["command"],"not":{"anyOf":[{"required":["executable"]},{"required":["argv"]},{"required":["input"]}]}},{"required":["executable"],"not":{"required":["command"]}}],"additionalProperties":false},
    handlerName: 'processStart',
    behavior: {"audit":"exec","cache":"workspace"},
  },
  {
    name: OP.PROCESS_READ,
    title: "Read Managed Process",
    description: "Read process state and new stdout/stderr ranges using independent byte cursors.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"processId":{"type":"string","minLength":1,"maxLength":200},"stdoutOffset":{"type":"number","minimum":0},"stderrOffset":{"type":"number","minimum":0},"maxBytes":{"type":"number","minimum":1000,"maximum":1048576},"includeMetadata":{"type":"boolean"},"metadataRevision":{"type":"string","minLength":1,"maxLength":100}},"required":["processId"],"additionalProperties":false},
    handlerName: 'processRead',
  },
  {
    name: OP.PROCESS_WRITE,
    title: "Write Managed Process Input",
    description: "Write bounded UTF-8 input to a running managed process. For pty:true processes, columns and rows may be supplied together to resize the pseudo-terminal; input may be omitted for a resize-only call.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"processId":{"type":"string","minLength":1,"maxLength":200},"input":{"type":"string","maxLength":1048576},"columns":{"type":"number","minimum":1,"maximum":1000},"rows":{"type":"number","minimum":1,"maximum":1000}},"required":["processId"],"anyOf":[{"required":["input"]},{"required":["columns","rows"]}],"additionalProperties":false},
    handlerName: 'processWrite',
    behavior: {"audit":"exec"},
  },
  {
    name: OP.PROCESS_STOP,
    title: "Stop Managed Process",
    description: "Stop a managed process and its process tree, then return final state and recent output.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"processId":{"type":"string","minLength":1,"maxLength":200},"graceMs":{"type":"number","minimum":0,"maximum":30000}},"required":["processId"],"additionalProperties":false},
    handlerName: 'processStop',
    behavior: {"audit":"exec"},
  },
  {
    name: OP.PROCESS_LIST,
    title: "List Managed Processes",
    description: "List active managed processes by default. Set includeTerminal:true to include recent exited, failed, or stopped records.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"status":{"type":"string","enum":["starting","running","stopping","exited","failed","stopped","orphaned"]},"activeOnly":{"type":"boolean"},"includeTerminal":{"type":"boolean"},"limit":{"type":"number","minimum":1,"maximum":500}},"required":[],"additionalProperties":false},
    handlerName: 'processList',
  },
  {
    name: OP.UI,
    title: "Local UI Test Session",
    description: "Operate a bounded local Chromium test session for a configured workspace.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"action":{"type":"string","enum":["start","navigate","snapshot","interact","screenshot","console","network","viewport","reload","stop"]},"sessionId":{"type":"string","pattern":"^ui_[A-Za-z0-9_-]{20,160}$"},"port":{"type":"number","minimum":1,"maximum":65535},"host":{"type":"string","enum":["localhost","127.0.0.1","::1","[::1]"]},"protocol":{"type":"string","enum":["http","https"]},"route":{"type":"string","minLength":1,"maxLength":4000},"allowedPorts":{"type":"array","items":{"type":"number","minimum":1,"maximum":65535},"maxItems":10},"headless":{"type":"boolean"},"width":{"type":"number","minimum":320,"maximum":3840},"height":{"type":"number","minimum":240,"maximum":2160},"timeoutMs":{"type":"number","minimum":100,"maximum":30000},"interaction":{"type":"string","enum":["click","fill","press","select","hover","wait"]},"target":{"type":"object","properties":{"by":{"type":"string","enum":["role","text","label","placeholder","testid","css"]},"value":{"type":"string","minLength":1,"maxLength":4000},"name":{"type":"string","maxLength":1000},"exact":{"type":"boolean"},"index":{"type":"number","minimum":0,"maximum":1000}},"required":["by","value"],"additionalProperties":false},"input":{"type":"string","maxLength":1048576},"key":{"type":"string","maxLength":100},"selectValue":{"type":"string","maxLength":10000},"state":{"type":"string","enum":["visible","hidden","attached","detached"]},"fullPage":{"type":"boolean"},"maxEntries":{"type":"number","minimum":1,"maximum":200},"clear":{"type":"boolean"}},"required":["workspace","action"],"additionalProperties":false},
    handlerName: 'ui',
    behavior: {"audit":"exec"},
  },
  {
    name: OP.SEARCH_SEMANTIC,
    title: "Hybrid Semantic Search",
    description: "Read-only. Rank local source files with persistent Tree-sitter structure, code-graph, Zoekt when available, FTS5 lexical, path, and symbol signals. Pass query for one search or queries for up to four independent searches that Rel.AI fans out inside one tool call. No neural model is used and no source text leaves the machine.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"query":{"type":"string","minLength":1,"maxLength":2000},"queries":{"type":"array","items":{"type":"string","minLength":1,"maxLength":2000},"minItems":1,"maxItems":4},"maxResults":{"type":"number","minimum":1,"maximum":100},"maxFiles":{"type":"number","minimum":1,"maximum":20000},"maxBytes":{"type":"number","minimum":1000,"maximum":393216},"pathPrefix":{"type":"string","maxLength":500},"language":{"type":"string","maxLength":80}},"required":["workspace"],"oneOf":[{"required":["query"],"not":{"required":["queries"]}},{"required":["queries"],"not":{"required":["query"]}}],"additionalProperties":false},
    handlerName: 'semanticSearch',
    behavior: {"longRunning":true},
  },
  {
    name: OP.VALIDATE_DIAGNOSTICS,
    title: "Run Structured Diagnostics",
    description: "Run detected or explicit language diagnostics and normalize file, line, column, severity, code, message, and source.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"command":{"type":"string","minLength":1,"maxLength":20000},"commands":{"type":"array","items":{"type":"string","minLength":1,"maxLength":20000},"minItems":1,"maxItems":50},"level":{"type":"string","enum":["quick","standard","release"]},"timeoutMs":{"type":"number","minimum":1000,"maximum":86400000},"maxResults":{"type":"number","minimum":1,"maximum":5000},"stopOnFailure":{"type":"boolean"}},"required":["workspace"],"additionalProperties":false},
    handlerName: 'diagnosticsRun',
    behavior: {"audit":"checks","summary":"checks","longRunning":true},
  },
  {
    name: OP.CHANGES_TIDY_PLAN,
    title: "Workspace Tidy Plan",
    description: "Read-only. Prepare a bounded workspace tidy plan for session-owned untracked artifacts. The server selects candidates; callers do not provide file paths.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"mode":{"type":"string","enum":["session_untracked"]},"maxCandidates":{"type":"number","minimum":1,"maximum":100}},"required":["workspace"],"additionalProperties":false},
    handlerName: 'tidyPlan',
    groups: ["cleanup"],
  },
  {
    name: OP.CHANGES_TIDY_RUN,
    title: "Run Workspace Tidy Plan",
    description: "Apply a previously prepared workspace tidy plan by planId. The plan is expiry-bound and hash-checked before any workspace change.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"planId":{"type":"string","minLength":20,"maxLength":120,"pattern":"^tidy_[A-Za-z0-9_-]+$"}},"required":["workspace","planId"],"additionalProperties":false},
    handlerName: 'tidyRun',
    groups: ["cleanup"],
    behavior: {"concurrencyScope":"workspace"},
  },
  {
    name: OP.VALIDATE_CHECKS,
    title: "Workspace Checks",
    description: "Run workspace validation checks (tests, linters, analyzers, build). Use level quick, standard, or release. Output is bounded to each step's tail where failures appear; pass fullOutput:true for a larger tail. For work that changed repository content, make the final validation call with complete:true and summary so validation and completion happen atomically. Use relai_work action 'finish' for read-only work, or when validation already passed without complete:true and no repository content changed afterward.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"level":{"type":"string","enum":["quick","standard","release"]},"check":{"type":"string","minLength":1,"maxLength":20000},"checks":{"type":"array","items":{"type":"string","minLength":1,"maxLength":20000},"minItems":1,"maxItems":50},"checksText":{"type":"string","minLength":1,"maxLength":100000},"timeoutMs":{"type":"number","minimum":1000,"maximum":86400000},"stopOnFailure":{"type":"boolean"},"fullOutput":{"type":"boolean"},"complete":{"type":"boolean"},"summary":{"type":"string","minLength":1,"maxLength":2000}},"required":["workspace"],"additionalProperties":false},
    handlerName: 'runChecks',
    behavior: {"audit":"checks","summary":"checks","longRunning":true},
  },
  {
    name: OP.VALIDATE_HTTP,
    title: "HTTP Route Probe",
    description: "Read-only. Check one configured local Rel.AI route such as /health or /dashboard and return reachability, HTTP status, final URL, response byte count, title, and bounded diagnostics. The route must be a local path.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"route":{"type":"string","minLength":1},"timeoutMs":{"type":"number","minimum":1000,"maximum":600000}},"required":["workspace","route"],"additionalProperties":false},
    handlerName: 'httpProbe',
    behavior: {"longRunning":true},
  },
  {
    name: OP.CHANGES_DIFF,
    title: "Review Local Repo Diff",
    description: "Read-only. Return repository status and current diff as a review artifact. Set redactSensitive:true to omit raw sensitive-file hunks and return metadata-only summaries; .env summaries identify added, removed, and changed key names without values. Pass path to filter to one file.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"staged":{"type":"boolean"},"path":{"type":"string"},"redactSensitive":{"type":"boolean"},"scope":{"type":"string","enum":["task","workspace"]},"maxBytes":{"type":"number","minimum":1000,"maximum":5242880}},"required":["workspace"],"additionalProperties":false},
    handlerName: 'diff',
    groups: ["audit"],
    behavior: {"summary":"diff"},
  },
  {
    name: OP.CHANGES_CHECKPOINT,
    title: "Checkpoint Review Artifact",
    description: "Create an immutable workspace-bound review checkpoint from the current task-scoped diff. The stored payload is integrity-checked and can be replayed later by checkpointId without depending on the current working tree.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"staged":{"type":"boolean"},"path":{"type":"string"},"redactSensitive":{"type":"boolean"},"scope":{"type":"string","enum":["task","workspace"]},"maxBytes":{"type":"number","minimum":1000,"maximum":5242880}},"required":["workspace"],"additionalProperties":false},
    handlerName: 'reviewCheckpoint',
    groups: ["audit"],
    behavior: {"summary":"diff"},
  },
  {
    name: OP.CHANGES_REPLAY,
    title: "Replay Review Checkpoint",
    description: "Read-only. Replay one immutable review checkpoint for the active workspace and verify its stored SHA-256 integrity digest before returning it.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"checkpointId":{"type":"string","minLength":24,"maxLength":180,"pattern":"^review_[A-Za-z0-9_-]+$"}},"required":["workspace","checkpointId"],"additionalProperties":false},
    handlerName: 'reviewReplay',
    groups: ["audit"],
  },
  {
    name: OP.CHANGES_RESTORE,
    title: "Restore Tracked Paths",
    description: "Restore only the listed tracked paths from HEAD. This does not remove untracked files and does not affect unrelated paths.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"paths":{"type":"array","items":{"type":"string"},"minItems":1,"maxItems":100}},"required":["workspace","paths"],"additionalProperties":false},
    handlerName: 'restorePaths',
    groups: ["cleanup"],
    behavior: {"cache":"paths","concurrencyScope":"workspace"},
  },
  {
    name: OP.CHANGES_RESET,
    title: "Reset Workspace State",
    description: "Discard all tracked working-tree and index changes by resetting to HEAD. Pass confirmation RESET. Set removeUntracked:true and confirmation RESET_AND_CLEAN to also remove untracked files and directories.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"confirmation":{"type":"string","enum":["RESET","RESET_AND_CLEAN"]},"removeUntracked":{"type":"boolean"}},"required":["workspace","confirmation"],"additionalProperties":false},
    handlerName: 'resetWorkspace',
    groups: ["cleanup"],
    behavior: {"cache":"workspace","concurrencyScope":"workspace"},
    dashboard: {"requiresApproval":true}
  },
  {
    name: OP.WORK_STATUS,
    title: "Workspace and Repository Status",
    description: "Read-only. Return configured workspace aliases and tool-surface status. When workspace is provided, also return command configuration, session policy, branch, ahead/behind counts, ownership-split changes, and untracked-file state under workspace.repository. When work_id is provided, also return the status and result of any long operation that continued after its connector request ended.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"maxBytes":{"type":"number","minimum":1000,"maximum":5242880}},"required":[],"additionalProperties":false},
    handlerName: 'status',
    behavior: {"taskScope":"optional"},
  },
  {
    name: OP.PUBLISH_COMMIT,
    title: "Record Commit",
    description: "Record a commit with an explicit message. Logical-task commits stay scoped to current task ownership by default; addAll:true explicitly selects all current visible workspace changes, including earlier, parallel-task, and ambient changes, and requires publish approval. Do not combine addAll:true with paths. Sensitive paths require sensitiveAuthorization:{ operation:'commit', paths:[...], reason:'...' }; every staged sensitive path must be listed.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"message":{"type":"string","minLength":1,"maxLength":4000},"dryRun":{"type":"boolean"},"addAll":{"type":"boolean"},"sensitiveAuthorization":{"type":"object","properties":{"operation":{"type":"string","enum":["commit"]},"paths":{"type":"array","items":{"type":"string","minLength":1,"maxLength":1000},"minItems":1,"maxItems":200},"reason":{"type":"string","minLength":1,"maxLength":500}},"required":["operation","paths","reason"],"additionalProperties":false},"paths":{"type":"array","items":{"type":"string","minLength":1,"maxLength":1000},"minItems":1,"maxItems":200},"maxBytes":{"type":"number","minimum":1000,"maximum":5242880},"timeoutMs":{"type":"number","minimum":1000,"maximum":86400000}},"required":["workspace","message"],"additionalProperties":false},
    handlerName: 'gitCommit',
    groups: ["git"],
    behavior: {"concurrencyScope":"workspace"},
  },
  {
    name: OP.PUBLISH_PUSH,
    title: "Publish Branch",
    description: "Publish a branch to a remote, with optional dry-run and set-upstream behavior.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"remote":{"type":"string","minLength":1,"maxLength":200},"branch":{"type":"string","minLength":1,"maxLength":500},"dryRun":{"type":"boolean"},"setUpstream":{"type":"boolean"},"timeoutMs":{"type":"number","minimum":1000,"maximum":240000}},"required":["workspace"],"additionalProperties":false},
    handlerName: 'gitPush',
    groups: ["git"],
    behavior: {"concurrencyScope":"workspace"},
  },
  {
    name: OP.PUBLISH_DRAFT_PR,
    title: "Draft Pull Request Text",
    description: "Read-only. Prepare a local pull-request title and body from a base/head Git diff. This does not call a hosting provider, create a remote pull request, push a branch, or modify the repository.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"base":{"type":"string"},"head":{"type":"string"},"title":{"type":"string"},"body":{"type":"string"}},"required":["workspace"],"additionalProperties":false},
    handlerName: 'gitDraftPr',
    groups: ["git","audit"],
  },
  {
    name: OP.EDIT,
    title: "Unified Workspace Edit",
    description: `The one tool for changing files directly in the configured visible workspace. Rel.AI serializes edit mutations against other workspace writes so successful changes are immediately visible to every task. Use semantic:{ action:'rename', path, line, column, newName } for language-server-authoritative symbol rename; the language server only proposes a WorkspaceEdit and Rel.AI retains path safety, stale guards, atomic application, rollback, auditing, and validation authority. Use symbolEdit:{ action, symbol, content, path? } for indexed structural replace/insert operations when a stable symbol is known. Use oldText/newText with optional occurrence or replacements:[...] for localized edits, content for complete-file text replacement, file for a native ChatGPT file reference to stream into path without overwrite, updateText for patch-shaped changes, or edits:[...] for an atomic batch of up to ${MAX_BATCH_EDITS} files. Rel.AI automatically stages large complete-file writes internally. Keep repository-wide patch-shaped changes together as one updateText request when the client transport can carry it; explicit stage start/append/commit remains available only as a transport fallback. expectedSha256 is supported for direct, staged, and batch file edits.`,
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"semantic":{"type":"object","properties":{"action":{"type":"string","enum":["rename"]},"path":{"type":"string","minLength":1,"maxLength":1000},"line":{"type":"number","minimum":1,"maximum":10000000},"column":{"type":"number","minimum":1,"maximum":10000000},"newName":{"type":"string","minLength":1,"maxLength":256}},"required":["action","path","line","column","newName"],"additionalProperties":false},"path":{"type":"string","minLength":1,"maxLength":1000},"oldText":{"type":"string"},"newText":{"type":"string"},"occurrence":{"type":"number","minimum":1,"maximum":1000000},"replacements":{"type":"array","items":{"type":"object","properties":{"oldText":{"type":"string"},"newText":{"type":"string"},"occurrence":{"type":"number","minimum":1,"maximum":1000000}},"required":["oldText","newText"],"additionalProperties":false},"minItems":1,"maxItems":50},"content":{"type":"string"},"file":{"type":"object","properties":{"download_url":{"type":"string","minLength":1,"maxLength":10000},"file_id":{"type":"string","minLength":1,"maxLength":512},"mime_type":{"type":"string","maxLength":500},"file_name":{"type":"string","maxLength":1000}},"required":["download_url","file_id"],"additionalProperties":false},"expectedSha256":{"type":"string","pattern":"^[a-fA-F0-9]{64}$"},"updateText":{"type":"string"},"envAction":{"type":"string","enum":["list","set","remove","compare"]},"key":{"type":"string","minLength":1,"maxLength":256},"value":{"type":"string","maxLength":65536},"templatePath":{"type":"string"},"edits":{"type":"array","items":{"type":"object","properties":{"path":{"type":"string"},"oldText":{"type":"string"},"newText":{"type":"string"},"occurrence":{"type":"number","minimum":1,"maximum":1000000},"replacements":{"type":"array","items":{"type":"object","properties":{"oldText":{"type":"string"},"newText":{"type":"string"},"occurrence":{"type":"number","minimum":1,"maximum":1000000}},"required":["oldText","newText"],"additionalProperties":false},"minItems":1,"maxItems":50},"content":{"type":"string"},"expectedSha256":{"type":"string","pattern":"^[a-fA-F0-9]{64}$"}},"required":["path"],"additionalProperties":false},"minItems":1,"maxItems":MAX_BATCH_EDITS},"runChecks":{"type":"boolean"},"level":{"type":"string","enum":["quick","standard","release"]},"returnDiff":{"type":"boolean"},"dryRun":{"type":"boolean"},"stage":{"type":"string","enum":["start","append","commit","abort"]},"writeId":{"type":"string","minLength":1,"maxLength":200},"symbolEdit":{"type":"object","properties":{"action":{"type":"string","enum":["replace","insert_before","insert_after"]},"symbol":{"type":"string","minLength":1,"maxLength":256},"content":{"type":"string"},"path":{"type":"string","minLength":1,"maxLength":1000}},"required":["action","symbol","content"],"additionalProperties":false}},"required":["workspace"],"oneOf":[{"required":["semantic"],"not":{"anyOf":[{"required":["symbolEdit"]},{"required":["path"]},{"required":["oldText"]},{"required":["replacements"]},{"required":["content"]},{"required":["file"]},{"required":["updateText"]},{"required":["edits"]},{"required":["envAction"]},{"required":["stage"]},{"required":["writeId"]}]}},{"required":["symbolEdit"],"not":{"anyOf":[{"required":["semantic"]},{"required":["path"]},{"required":["oldText"]},{"required":["replacements"]},{"required":["content"]},{"required":["file"]},{"required":["updateText"]},{"required":["edits"]},{"required":["envAction"]},{"required":["stage"]},{"required":["writeId"]}]}},{"required":["path","oldText","newText"],"not":{"anyOf":[{"required":["symbolEdit"]},{"required":["semantic"]},{"required":["replacements"]},{"required":["content"]},{"required":["file"]},{"required":["updateText"]},{"required":["edits"]},{"required":["envAction"]},{"required":["stage"]}]}},{"required":["path","replacements"],"not":{"anyOf":[{"required":["symbolEdit"]},{"required":["semantic"]},{"required":["oldText"]},{"required":["content"]},{"required":["file"]},{"required":["updateText"]},{"required":["edits"]},{"required":["envAction"]},{"required":["stage"]}]}},{"required":["path","content"],"not":{"anyOf":[{"required":["symbolEdit"]},{"required":["semantic"]},{"required":["oldText"]},{"required":["replacements"]},{"required":["file"]},{"required":["updateText"]},{"required":["edits"]},{"required":["envAction"]},{"required":["stage"]}]}},{"required":["path","file"],"not":{"anyOf":[{"required":["symbolEdit"]},{"required":["semantic"]},{"required":["oldText"]},{"required":["replacements"]},{"required":["content"]},{"required":["updateText"]},{"required":["edits"]},{"required":["envAction"]},{"required":["stage"]}]}},{"required":["updateText"],"not":{"anyOf":[{"required":["symbolEdit"]},{"required":["semantic"]},{"required":["oldText"]},{"required":["replacements"]},{"required":["content"]},{"required":["file"]},{"required":["edits"]},{"required":["envAction"]},{"required":["stage"]}]}},{"required":["edits"],"not":{"anyOf":[{"required":["symbolEdit"]},{"required":["semantic"]},{"required":["oldText"]},{"required":["replacements"]},{"required":["content"]},{"required":["file"]},{"required":["updateText"]},{"required":["envAction"]},{"required":["stage"]}]}},{"required":["envAction"],"not":{"anyOf":[{"required":["symbolEdit"]},{"required":["semantic"]},{"required":["oldText"]},{"required":["replacements"]},{"required":["content"]},{"required":["file"]},{"required":["updateText"]},{"required":["edits"]},{"required":["stage"]}]}},{"required":["stage"],"not":{"anyOf":[{"required":["symbolEdit"]},{"required":["semantic"]},{"required":["oldText"]},{"required":["replacements"]},{"required":["file"]},{"required":["edits"]},{"required":["envAction"]}]}}],"additionalProperties":false},
    handlerName: 'edit',
    behavior: {"audit":"edit","cache":"edit","startsSession":true,"deferStagedSession":true,"sessionWrite":true,"summary":"edit","longRunning":true,"concurrencyScope":"mutation"},
  },
  {
    name: OP.WORK_CANCEL,
    title: "Cancel Logical Task",
    description: "Cancel the exact logical task identified by work_id. Cancellation is idempotent, preserves partial progress and final timestamps, records a bounded reason, and cooperatively aborts active subprocess-backed operations when supported.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"reason":{"type":"string","maxLength":500}},"required":[],"additionalProperties":false},
    handlerName: 'cancelTask',
    behavior: {"audit":"exec"},
    dashboard: {"category":"Workflow"}
  },
  {
    name: OP.WORK_FINISH,
    title: "Report Task Completion",
    description: "Explicitly close the task identified by work_id after read-only work, or after validation already passed without complete:true and no repository content changed afterward. For work that changed repository content, prefer the final relai_validate action 'checks' call with complete:true and summary so validation and completion happen atomically. Validation and mutation checks are restricted to that exact logical task; Rel.AI never falls back to another task in the workspace.",
    inputSchema: {"type":"object","properties":{"workspace":{"type":"string"},"summary":{"type":"string","minLength":1,"maxLength":2000}},"required":["workspace","summary"],"additionalProperties":false},
    handlerName: 'completeTask',
    behavior: {"audit":"completion","summary":"completion","concurrencyScope":"mutation"},
    dashboard: {"category":"Workflow"}
  },
];

export { OPERATION_DEFINITION_VALUES };
