const STRING = { type: 'string' };
const STRING_NULL = { type: ['string', 'null'] };
const NUMBER = { type: 'number' };
const NUMBER_NULL = { type: ['number', 'null'] };
const TIMESTAMP_NULL = { type: ['string', 'number', 'null'] };
const BOOLEAN = { type: 'boolean' };
const OBJECT = { type: 'object', additionalProperties: true };
const ARRAY = { type: 'array', items: OBJECT };
const STRING_ARRAY = { type: 'array', items: STRING };

const FIELD_SCHEMAS = Object.freeze({
  ok: BOOLEAN,
  version: STRING,
  workspace: { type: ['string', 'object', 'null'], additionalProperties: true },
  workspaceId: STRING,
  id: STRING,
  sourcePath: STRING,
  owningTaskId: STRING,
  createdAt: STRING,
  sessionId: STRING,
  url: STRING,
  origin: STRING,
  browserEngine: STRING,
  browserProduct: STRING,
  allowedPorts: { type: 'array', items: NUMBER },
  viewport: OBJECT,
  snapshot: STRING,
  consoleEntries: ARRAY,
  networkEntries: ARRAY,
  target: OBJECT,
  interaction: STRING,
  image: OBJECT,
  root: STRING,
  toolMode: STRING,
  trustedLocalAgent: BOOLEAN,
  manifests: STRING_ARRAY,
  manifestContents: OBJECT,
  discoveredCommands: OBJECT,
  fileCount: NUMBER,
  effectiveMaxEntries: NUMBER,
  budgetMultiplied: BOOLEAN,
  hints: STRING_ARRAY,
  recommendedFlow: STRING_ARRAY,
  writeGuidance: OBJECT,
  operationJournal: { type: ['object', 'array'], additionalProperties: true, items: OBJECT },
  work_id: STRING,
  taskId: STRING,
  status: STRING,
  staged: BOOLEAN,
  redactSensitive: BOOLEAN,
  reviewScope: STRING,
  reviewedScope: STRING,
  reviewHash: STRING,
  reviewedFiles: STRING_ARRAY,
  excludedWorkspaceFiles: STRING_ARRAY,
  aheadBehind: { type: ['object', 'null'], additionalProperties: true },
  statusEntries: ARRAY,
  sessionChangedFiles: STRING_ARRAY,
  baselineChangedFiles: STRING_ARRAY,
  untrackedSessionFiles: STRING_ARRAY,
  untrackedBaselineFiles: STRING_ARRAY,
  baselineSource: STRING,
  sensitiveReview: ARRAY,
  sensitiveValuesReturned: BOOLEAN,
  identity: STRING,
  objective: STRING,
  bootstrap: OBJECT,
  workspaceBinding: OBJECT,
  nextAction: STRING,
  message: STRING,
  error: { type: ['string', 'object', 'null'], additionalProperties: true },
  errorCode: STRING,
  errorDetails: OBJECT,
  recovery: OBJECT,
  files: { type: 'array', items: { type: ['string', 'object'], additionalProperties: true } },
  items: ARRAY,
  results: ARRAY,
  definitions: ARRAY,
  references: ARRAY,
  related: ARRAY,
  impactedPaths: ARRAY,
  affectedTests: STRING_ARRAY,
  diagnostics: ARRAY,
  processes: ARRAY,
  candidates: ARRAY,
  candidateCount: NUMBER,
  skippedCount: NUMBER,
  ttlSeconds: NUMBER,
  reason: STRING,
  applied: ARRAY,
  appliedCount: NUMBER,
  refused: ARRAY,
  skipped: ARRAY,
  changedFiles: STRING_ARRAY,
  dryRun: BOOLEAN,
  addAll: BOOLEAN,
  add: OBJECT,
  commit: OBJECT,
  push: OBJECT,
  setUpstream: BOOLEAN,
  remote: STRING,
  sensitiveAuthorization: OBJECT,
  statusBefore: OBJECT,
  statusAfter: OBJECT,
  secretStagedFiles: STRING_ARRAY,
  unauthorizedSecretPaths: STRING_ARRAY,
  indexRestored: BOOLEAN,
  head: STRING,
  body: STRING,
  changedFileCount: NUMBER,
  emptyDiff: BOOLEAN,
  draftOnly: BOOLEAN,
  remoteChanged: BOOLEAN,
  warning: STRING,
  operationId: STRING,
  changed: BOOLEAN,
  oldSha256: STRING_NULL,
  newSha256: STRING_NULL,
  replacements: ARRAY,
  verified: BOOLEAN,
  bytes: NUMBER,
  originalBytes: NUMBER,
  plannerPath: STRING,
  plannerReason: STRING,
  result: OBJECT,
  writeId: STRING,
  chunks: NUMBER,
  cleared: BOOLEAN,
  editCount: NUMBER,
  preflightAtomic: BOOLEAN,
  rollbackAtomic: BOOLEAN,
  batchInputBytes: NUMBER,
  replacementCount: NUMBER,
  snapshotBytes: NUMBER,
  resultDetailsCompacted: BOOLEAN,
  rollback: OBJECT,
  preflight: ARRAY,
  touchedPaths: STRING_ARRAY,
  patchBytes: NUMBER,
  sourceFormat: STRING,
  converted: BOOLEAN,
  backup: { type: ['object', 'string', 'null'], additionalProperties: true },
  verify: OBJECT,
  apply: OBJECT,
  shaMismatch: OBJECT,
  commands: STRING_ARRAY,
  command: STRING,
  checks: { type: ['object', 'array'], additionalProperties: true, items: STRING },
  skippedChecks: ARRAY,
  projectInstructions: OBJECT,
  repository: OBJECT,
  runtime: OBJECT,
  repositoryRuntime: OBJECT,
  runtimeCompatibility: OBJECT,
  git: OBJECT,
  diff: { type: ['string', 'object'], additionalProperties: true },
  summary: { type: ['string', 'object'], additionalProperties: true },
  validationStatus: STRING,
  validated: BOOLEAN,
  validationLevel: STRING,
  validationLevelReason: STRING,
  validationFingerprint: STRING,
  validationAt: STRING_NULL,
  completionKnown: BOOLEAN,
  completionSource: STRING,
  endReason: STRING,
  terminalReason: STRING,
  cancelledAt: TIMESTAMP_NULL,
  progress: OBJECT,
  duplicate: BOOLEAN,
  reused: BOOLEAN,
  count: NUMBER,
  completedUnits: NUMBER,
  executedUnits: NUMBER,
  reusedUnits: NUMBER,
  reusedChecks: STRING_ARRAY,
  totalUnits: NUMBER,
  resultCount: NUMBER,
  diagnosticCount: NUMBER,
  toolCount: NUMBER,
  workspaceCount: NUMBER,
  durationMs: NUMBER,
  exitCode: NUMBER_NULL,
  stdout: { type: ['string', 'object'], additionalProperties: true },
  stderr: { type: ['string', 'object'], additionalProperties: true },
  stdoutBytes: NUMBER,
  stderrBytes: NUMBER,
  stdoutTruncated: BOOLEAN,
  stderrTruncated: BOOLEAN,
  timedOut: BOOLEAN,
  cancelled: BOOLEAN,
  terminationConfirmed: BOOLEAN,
  forcedTermination: BOOLEAN,
  signal: STRING_NULL,
  truncated: BOOLEAN,
  changedFilesTruncated: BOOLEAN,
  mutationTracking: STRING,
  environmentKeys: STRING_ARRAY,
  cacheHit: BOOLEAN,
  fingerprint: STRING,
  strategy: STRING,
  privacy: STRING,
  processId: STRING,
  pid: NUMBER_NULL,
  label: STRING,
  commandSummary: STRING,
  cwd: STRING,
  shell: STRING,
  lifecycle: STRING,
  kind: STRING,
  purpose: STRING,
  metadataRevision: STRING,
  originatingTaskId: STRING_NULL,
  workSessionId: STRING_NULL,
  startedAt: STRING,
  endedAt: TIMESTAMP_NULL,
  stdoutRetainedFromOffset: NUMBER,
  stderrRetainedFromOffset: NUMBER,
  stdoutTail: STRING,
  stderrTail: STRING,
  acceptedBytes: NUMBER,
  readiness: OBJECT,
  alias: STRING,
  sourceAlias: STRING,
  path: STRING,
  paths: STRING_ARRAY,
  branch: STRING,
  base: STRING,
  dirty: BOOLEAN,
  available: BOOLEAN,
  stale: BOOLEAN,
  removedPath: STRING,
  branchPreserved: BOOLEAN,
  query: STRING,
  action: STRING,
  index: OBJECT,
  language: STRING,
  languages: OBJECT,
  discoveryWarnings: ARRAY,
  diagnosticCommands: ARRAY,
  validationCommands: OBJECT,
  configuredTestCommands: ARRAY,
  diagnosticsExecuted: BOOLEAN,
  next: STRING,
  semanticEmbeddings: BOOLEAN,
  neuralEmbeddings: BOOLEAN,
  pattern: STRING,
  glob: STRING,
  fixed: BOOLEAN,
  ignoreCase: BOOLEAN,
  matches: ARRAY,
  contextBefore: NUMBER,
  contextAfter: NUMBER,
  groupByFile: BOOLEAN,
  mergeOverlaps: BOOLEAN,
  maxFiles: NUMBER,
  maxRangesPerFile: NUMBER,
  maxRangeLines: NUMBER,
  returnedFileCount: NUMBER,
  returnedRangeCount: NUMBER,
  contextMatchCount: NUMBER,
  returnedBytes: NUMBER,
  maxBytes: NUMBER,
  omittedFiles: NUMBER,
  omittedRanges: NUMBER,
  contextTruncated: BOOLEAN,
  matchCount: NUMBER,
  symbol: STRING,
  definitionCount: NUMBER,
  referenceCount: NUMBER,
  callCount: NUMBER,
  calls: ARRAY,
  seeds: STRING_ARRAY,
  maxDepth: NUMBER,
  impactedPathCount: NUMBER,
  importEdges: ARRAY,
  definitionPaths: STRING_ARRAY,
  directCallers: ARRAY,
  importers: ARRAY,
  indirectImpact: ARRAY,
  relatedSymbols: ARRAY,
  uiSurfaces: ARRAY,
  registrationSurfaces: ARRAY,
  recommendedReadOrder: STRING_ARRAY,
  architecture: OBJECT,
  relationshipTypes: OBJECT,
  modules: ARRAY,
  entryPoints: ARRAY,
  hotspots: ARRAY,
  layers: ARRAY,
  communities: ARRAY,
  planId: STRING,
  signature: STRING,
  expiresAt: STRING,
  recommended: STRING,
  planSelection: STRING,
  level: STRING,
  fullOutput: BOOLEAN,
  planCreatedAt: STRING,
  failedCheck: STRING,
  route: STRING,
  reachable: BOOLEAN,
  statusCode: NUMBER_NULL,
  finalUrl: STRING,
  responseBytes: NUMBER,
  title: STRING,
  mode: STRING,
  effectiveMode: STRING,
  autoTier: STRING,
  selectionStrategy: STRING,
  check: STRING,
  availableChecks: STRING_ARRAY,
  plan: OBJECT,
  operation: { type: ['string', 'object'], additionalProperties: true },
  state: STRING,
  removeUntracked: BOOLEAN,
  reset: OBJECT,
  clean: OBJECT,
  toolSurface: OBJECT,
  tools: STRING_ARRAY,
  toolGroups: OBJECT,
  scripts: STRING_ARRAY,
  ci: OBJECT,
  workspaceAliases: STRING_ARRAY,
  authorizationCodes: NUMBER,
  accessTokens: NUMBER,
  refreshTokens: NUMBER,
  registeredClients: NUMBER,
  aliasNormalizations: NUMBER,
  policy: OBJECT,
  workflow: OBJECT
});

const TOOL_FIELDS = Object.freeze({
  relai_begin_work: ['ok', 'workspace', 'work_id', 'status', 'identity', 'title', 'objective', 'workspaceBinding', 'bootstrap', 'nextAction'],
  relai_repo_snapshot: ['ok', 'workspace', 'work_id', 'root', 'toolMode', 'trustedLocalAgent', 'manifests', 'manifestContents', 'discoveredCommands', 'projectInstructions', 'fileCount', 'effectiveMaxEntries', 'budgetMultiplied', 'files', 'returnedFileCount', 'omittedFiles', 'skipped', 'skippedCount', 'truncated', 'hints', 'git', 'recommendedFlow', 'writeGuidance', 'operationJournal', 'repository', 'changedFiles', 'next'],
  relai_read: ['ok', 'workspace', 'work_id', 'items', 'skipped', 'truncated'],
  relai_search: ['ok', 'workspace', 'work_id', 'pattern', 'glob', 'fixed', 'ignoreCase', 'matches', 'matchCount', 'mode', 'effectiveMode', 'autoTier', 'selectionStrategy', 'contextBefore', 'contextAfter', 'groupByFile', 'mergeOverlaps', 'maxFiles', 'maxRangesPerFile', 'maxRangeLines', 'files', 'results', 'resultCount', 'returnedFileCount', 'returnedRangeCount', 'contextMatchCount', 'returnedBytes', 'maxBytes', 'omittedFiles', 'omittedRanges', 'truncated', 'contextTruncated', 'next'],
  relai_code_inspect: ['ok', 'workspace', 'work_id', 'action', 'index', 'query', 'strategy', 'semanticEmbeddings', 'files', 'matchCount', 'symbol', 'definitions', 'definitionCount', 'references', 'items', 'referenceCount', 'callCount', 'calls', 'seeds', 'maxDepth', 'impactedPaths', 'impactedPathCount', 'affectedTests', 'importEdges', 'definitionPaths', 'directCallers', 'importers', 'indirectImpact', 'relatedSymbols', 'uiSurfaces', 'registrationSurfaces', 'recommendedReadOrder', 'architecture', 'relationshipTypes', 'modules', 'entryPoints', 'hotspots', 'layers', 'communities', 'languages', 'diagnosticCommands', 'discoveryWarnings', 'validationCommands', 'configuredTestCommands', 'diagnosticsExecuted', 'summary', 'truncated', 'next'],
  relai_exec: ['ok', 'workspace', 'work_id', 'command', 'commandSummary', 'cwd', 'shell', 'durationMs', 'exitCode', 'stdout', 'stderr', 'stdoutBytes', 'stderrBytes', 'stdoutTruncated', 'stderrTruncated', 'timedOut', 'cancelled', 'terminationConfirmed', 'forcedTermination', 'signal', 'error', 'environmentKeys', 'changedFiles', 'changedFilesTruncated', 'mutationTracking'],
  relai_process_start: ['ok', 'work_id', 'processId', 'pid', 'workspace', 'workspaceId', 'label', 'kind', 'purpose', 'metadataRevision', 'commandSummary', 'cwd', 'status', 'reused', 'readiness', 'lifecycle', 'originatingTaskId', 'workSessionId', 'startedAt', 'endedAt', 'exitCode', 'signal', 'stdoutBytes', 'stderrBytes', 'stdoutRetainedFromOffset', 'stderrRetainedFromOffset', 'environmentKeys', 'stdoutTail', 'stderrTail', 'readiness', 'error'],
  relai_process_read: ['ok', 'work_id', 'processId', 'pid', 'workspace', 'workspaceId', 'label', 'kind', 'purpose', 'metadataRevision', 'commandSummary', 'cwd', 'status', 'reused', 'readiness', 'lifecycle', 'originatingTaskId', 'workSessionId', 'startedAt', 'endedAt', 'exitCode', 'signal', 'stdoutBytes', 'stderrBytes', 'stdoutRetainedFromOffset', 'stderrRetainedFromOffset', 'environmentKeys', 'stdout', 'stderr', 'error'],
  relai_process_write: ['ok', 'work_id', 'processId', 'acceptedBytes', 'status'],
  relai_process_stop: ['ok', 'work_id', 'processId', 'pid', 'workspace', 'workspaceId', 'label', 'kind', 'purpose', 'metadataRevision', 'commandSummary', 'cwd', 'status', 'reused', 'readiness', 'lifecycle', 'originatingTaskId', 'workSessionId', 'startedAt', 'endedAt', 'exitCode', 'signal', 'stdoutBytes', 'stderrBytes', 'stdoutRetainedFromOffset', 'stderrRetainedFromOffset', 'environmentKeys', 'stdoutTail', 'stderrTail', 'duplicate', 'error'],
  relai_process_list: ['ok', 'work_id', 'processes', 'count'],
  relai_ui: ['ok', 'workspace', 'work_id', 'action', 'sessionId', 'url', 'origin', 'statusCode', 'title', 'viewport', 'browserEngine', 'browserProduct', 'allowedPorts', 'createdAt', 'snapshot', 'truncated', 'interaction', 'target', 'image', 'consoleEntries', 'networkEntries', 'count', 'cleared', 'status', 'error'],
  relai_semantic_search: ['ok', 'workspace', 'work_id', 'query', 'strategy', 'privacy', 'fingerprint', 'cacheHit', 'neuralEmbeddings', 'results', 'resultCount', 'truncated'],
  relai_diagnostics_run: ['ok', 'workspace', 'work_id', 'commands', 'results', 'diagnostics', 'diagnosticCount', 'completedUnits', 'totalUnits', 'cancelled', 'truncated', 'message'],
  relai_tidy_plan: ['ok', 'workspace', 'work_id', 'operation', 'mode', 'planId', 'expiresAt', 'ttlSeconds', 'candidateCount', 'skippedCount', 'candidates', 'skipped', 'reason', 'message', 'next'],
  relai_tidy_run: ['ok', 'workspace', 'work_id', 'operation', 'planId', 'changed', 'changedFiles', 'appliedCount', 'applied', 'refused', 'message'],
  relai_run_checks: ['ok', 'workspace', 'work_id', 'duplicate', 'level', 'checks', 'commands', 'results', 'skippedChecks', 'completedUnits', 'executedUnits', 'reusedUnits', 'reusedChecks', 'totalUnits', 'failedCheck', 'cancelled', 'summary', 'validated', 'validationStatus', 'validationLevel', 'validationLevelReason', 'validationFingerprint', 'validationAt', 'completionKnown', 'completionSource', 'endReason', 'planId', 'planSelection', 'planCreatedAt', 'fullOutput', 'changedFiles', 'aliasNormalizations', 'policy', 'message', 'nextAction'],
  relai_http_probe: ['ok', 'workspace', 'work_id', 'route', 'reachable', 'statusCode', 'finalUrl', 'responseBytes', 'title', 'error'],
  relai_diff: ['ok', 'workspace', 'work_id', 'staged', 'redactSensitive', 'path', 'reviewScope', 'reviewedScope', 'reviewHash', 'reviewedFiles', 'excludedWorkspaceFiles', 'status', 'branch', 'aheadBehind', 'statusEntries', 'sessionChangedFiles', 'baselineChangedFiles', 'untrackedSessionFiles', 'untrackedBaselineFiles', 'baselineSource', 'diff', 'sensitiveReview', 'sensitiveValuesReturned', 'exitCode', 'stderr'],
  relai_restore_paths: ['ok', 'workspace', 'work_id', 'mode', 'paths', 'command', 'commandSummary', 'cwd', 'shell', 'durationMs', 'exitCode', 'stdout', 'stderr', 'stdoutBytes', 'stderrBytes', 'stdoutTruncated', 'stderrTruncated', 'timedOut', 'cancelled', 'terminationConfirmed', 'forcedTermination', 'signal', 'error'],
  relai_reset_workspace: ['ok', 'workspace', 'work_id', 'mode', 'removeUntracked', 'reset', 'clean'],
  relai_status: ['ok', 'version', 'workspace', 'work_id', 'workspaceAliases', 'workspaceCount', 'toolSurface', 'tools', 'toolGroups', 'scripts', 'ci', 'runtime', 'repositoryRuntime', 'runtimeCompatibility', 'repository', 'readiness', 'state'],
  relai_git_commit: ['ok', 'workspace', 'work_id', 'dryRun', 'message', 'addAll', 'paths', 'sensitiveAuthorization', 'statusBefore', 'add', 'commit', 'statusAfter', 'secretStagedFiles', 'unauthorizedSecretPaths', 'indexRestored', 'error'],
  relai_git_push: ['ok', 'workspace', 'work_id', 'remote', 'branch', 'dryRun', 'setUpstream', 'push'],
  relai_git_draft_pr: ['ok', 'workspace', 'work_id', 'base', 'head', 'title', 'body', 'changedFiles', 'changedFileCount', 'emptyDiff', 'draftOnly', 'remoteChanged', 'warning', 'diff'],
  relai_edit: ['ok', 'workspace', 'work_id', 'dryRun', 'operationId', 'operation', 'path', 'changed', 'changedFiles', 'oldSha256', 'newSha256', 'shaMismatch', 'replacements', 'verified', 'bytes', 'plannerPath', 'plannerReason', 'result', 'writeId', 'chunks', 'cleared', 'staged', 'editCount', 'appliedCount', 'preflightAtomic', 'rollbackAtomic', 'batchInputBytes', 'replacementCount', 'snapshotBytes', 'resultDetailsCompacted', 'rollback', 'preflight', 'results', 'touchedPaths', 'patchBytes', 'sourceFormat', 'converted', 'backup', 'verify', 'apply', 'check', 'diagnostics', 'checks', 'diff', 'summary', 'validationStatus', 'error', 'next'],
  relai_cancel_work: ['ok', 'workspace', 'work_id', 'status', 'duplicate', 'endReason', 'terminalReason', 'endedAt', 'cancelledAt', 'progress'],
  relai_finish_work: ['ok', 'workspace', 'work_id', 'duplicate', 'completionKnown', 'endReason', 'completionSource', 'summary', 'validationStatus', 'validationLevel', 'validationAt', 'validationFingerprint', 'changedFiles', 'message']
});

const SUCCESS_REQUIRED_FIELDS = Object.freeze({
  relai_exec: ['workspace', 'work_id', 'exitCode', 'durationMs'],
  relai_diagnostics_run: ['workspace', 'work_id', 'diagnostics', 'diagnosticCount'],
  relai_run_checks: ['workspace', 'work_id', 'results', 'validationStatus'],
  relai_process_start: ['work_id', 'processId', 'status', 'lifecycle'],
  relai_process_read: ['work_id', 'processId', 'status', 'stdout', 'stderr'],
  relai_process_write: ['work_id', 'processId', 'acceptedBytes', 'status'],
  relai_process_stop: ['work_id', 'processId', 'status', 'duplicate'],
  relai_process_list: ['work_id', 'processes', 'count'],
  relai_cancel_work: ['work_id', 'status', 'duplicate'],
  relai_finish_work: ['work_id', 'completionKnown', 'validationStatus']
});

const CLOSED_SUCCESS_TOOLS = new Set(Object.keys(TOOL_FIELDS));
const COMPACT_RESULT_FIELDS = Object.freeze([
  'ok', 'truncated', 'originalBytes', 'workspace', 'work_id', 'processId', 'status', 'duplicate',
  'mode', 'check', 'exitCode', 'durationMs', 'diagnosticCount', 'validationStatus', 'completionKnown',
  'message', 'error', 'errorCode', 'level', 'summary', 'nextAction', 'stdout', 'stderr', 'results'
]);

function outputSchemaFor(name) {
  const fields = [...new Set([
    ...(TOOL_FIELDS[name] || ['ok', 'workspace', 'work_id', 'message', 'error', 'errorCode', 'nextAction']),
    ...COMPACT_RESULT_FIELDS,
    'workflow'
  ])];
  const properties = Object.fromEntries(fields.map(field => [field, FIELD_SCHEMAS[field] || OBJECT]));
  const successRequired = ['ok', ...(SUCCESS_REQUIRED_FIELDS[name] || [])];
  return {
    type: 'object',
    properties,
    required: ['ok'],
    oneOf: [
      {
        type: 'object',
        properties: { ...properties, ok: { const: true } },
        required: successRequired,
        additionalProperties: !CLOSED_SUCCESS_TOOLS.has(name)
      },
      {
        type: 'object',
        properties: {
          ...properties,
          ok: { const: false },
          error: FIELD_SCHEMAS.error,
          errorCode: FIELD_SCHEMAS.errorCode,
          errorDetails: FIELD_SCHEMAS.errorDetails,
          message: FIELD_SCHEMAS.message,
          nextAction: FIELD_SCHEMAS.nextAction,
          title: FIELD_SCHEMAS.title,
          recovery: FIELD_SCHEMAS.recovery
        },
        required: ['ok', 'error'],
        additionalProperties: true
      }
    ]
  };
}

export {
  outputSchemaFor,




};
